import { MovieItemAttr, TvShowItemAttr } from "../Section/types";

export const dummyMovies: MovieItemAttr[] = [
  {
    id: 547016,
    video: false,
    vote_count: 669,
    vote_average: 7.3,
    title: "The Old Guard",
    release_date: "2020-07-10",
    original_language: "en",
    original_title: "The Old Guard",
    genre_ids: [28, 14],
    backdrop_path: "/m0ObOaJBerZ3Unc74l471ar8Iiy.jpg",
    adult: false,
    overview:
      "Four undying warriors who've secretly protected humanity for centuries become targeted for their mysterious powers just as they discover a new immortal.",
    poster_path: "/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg",
    popularity: 351.438,
    media_type: "movie",
  },
  {
    id: 516486,
    video: false,
    vote_count: 148,
    vote_average: 7,
    title: "Greyhound",
    release_date: "2020-07-10",
    original_language: "en",
    original_title: "Greyhound",
    genre_ids: [28, 18, 10752],
    backdrop_path: "/xXBnM6uSTk6qqCf0SRZKXcga9Ba.jpg",
    adult: false,
    overview:
      "A first-time captain leads a convoy of allied ships carrying thousands of soldiers across the treacherous waters of the “Black Pit” to the front lines of WW2. With no air cover protection for 5 days, the captain and his convoy must battle the surrounding enemy Nazi U-boats in order to give the allies a chance to win the war.",
    poster_path: "/AsdB9A2XGalCZVjlyG9tRf03IfW.jpg",
    popularity: 351.193,
    media_type: "movie",
  },
  {
    id: 587792,
    video: false,
    vote_count: 105,
    vote_average: 7.9,
    title: "Palm Springs",
    release_date: "2020-01-26",
    original_language: "en",
    original_title: "Palm Springs",
    genre_ids: [35, 878, 10749],
    backdrop_path: "/d7JUXVvjvVCXWs1mlpyO5ESdWdT.jpg",
    adult: false,
    overview:
      "When carefree Nyles and reluctant maid of honor Sarah have a chance encounter at a Palm Springs wedding, things get complicated as they are unable to escape the venue, themselves, or each other.",
    poster_path: "/yf5IuMW6GHghu39kxA0oFx7Bxmj.jpg",
    popularity: 66.585,
    media_type: "movie",
  },
  {
    id: 299534,
    video: false,
    vote_count: 14114,
    vote_average: 8.3,
    title: "Avengers: Endgame",
    release_date: "2019-04-24",
    original_language: "en",
    original_title: "Avengers: Endgame",
    genre_ids: [28, 12, 878],
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    adult: false,
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    popularity: 72.622,
    media_type: "movie",
  },
  {
    id: 539181,
    video: false,
    vote_count: 32,
    vote_average: 6.6,
    title: "Relic",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Relic",
    genre_ids: [18, 27],
    backdrop_path: "/vpUUznNzW85xo02H16RaSxRNS1.jpg",
    adult: false,
    overview:
      "When Edna, the elderly and widowed matriarch of the family, goes missing, her daughter Kay and granddaughter Sam travel to their remote family home to find her. Soon after her return, they start to discover a sinister presence haunting the house and taking control of Edna.",
    poster_path: "/3wZ0gxLqsPleneFSTZILmM3BE8Q.jpg",
    popularity: 87.111,
    media_type: "movie",
  },
  {
    id: 606234,
    video: false,
    vote_count: 7,
    vote_average: 8.4,
    title: "Archive",
    release_date: "2020-07-01",
    original_language: "en",
    original_title: "Archive",
    genre_ids: [878],
    backdrop_path: "/ckRBJIHrUhQMMkEhuk4iW2NIBWP.jpg",
    adult: false,
    overview:
      "2038: George Almore is working on a true human-equivalent AI, and his latest prototype is almost ready. This sensitive phase is also the riskiest as he has a goal that must be hidden at all costs—being reunited with his dead wife.",
    poster_path: "/q9t1AxbzyGQENDunK1GT8OS4aJl.jpg",
    popularity: 53.994,
    media_type: "movie",
  },
  {
    id: 556574,
    video: false,
    vote_count: 220,
    vote_average: 8.6,
    title: "Hamilton",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Hamilton",
    genre_ids: [18, 36, 10402],
    backdrop_path: "/uWVkEo9PWHu9algZsiLPi6sRU64.jpg",
    adult: false,
    overview:
      "Presenting the tale of American founding father Alexander Hamilton, this filmed version of the original Broadway smash hit is the story of America then, told by America now.",
    poster_path: "/h1B7tW0t399VDjAcWJh8m87469b.jpg",
    popularity: 82.625,
    media_type: "movie",
  },
  {
    id: 385103,
    video: false,
    vote_count: 1226,
    vote_average: 8,
    title: "Scoob!",
    release_date: "2020-05-15",
    original_language: "en",
    original_title: "Scoob!",
    genre_ids: [12, 16, 35, 9648, 10751],
    backdrop_path: "/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg",
    adult: false,
    overview:
      "In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.",
    poster_path: "/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg",
    popularity: 100.079,
    media_type: "movie",
  },
  {
    id: 11,
    video: false,
    vote_count: 13945,
    vote_average: 8.2,
    title: "Star Wars",
    release_date: "1977-05-25",
    original_language: "en",
    original_title: "Star Wars",
    genre_ids: [28, 12, 878],
    backdrop_path: "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
    adult: false,
    overview:
      "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
    poster_path: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    popularity: 68.052,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/yOBBzBlN72C6QLtXaskQ87fdVkS.jpg",
    genre_ids: [28, 12, 36],
    id: 635237,
    original_language: "fr",
    original_title: "Arthur & Merlin: Knights of Camelot",
    overview:
      "King Arthur returns home after fighting the Roman Empire. His illegitimate son has corrupted the throne of Camelot and King Arthur must reunite with the wizard Merlin and the Knights of the Round Table to fight to get back his crown.",
    poster_path: "/chGTXsvn53XvEnvsJ9ZD9eiYKx9.jpg",
    release_date: "2020-05-28",
    title: "Arthur & Merlin: Knights of Camelot",
    video: false,
    vote_average: 2.1,
    vote_count: 8,
    popularity: 4.74,
    media_type: "movie",
  },
  {
    id: 495764,
    video: false,
    vote_count: 4953,
    vote_average: 7.2,
    title:
      "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
    release_date: "2020-02-05",
    original_language: "en",
    original_title:
      "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
    genre_ids: [28, 35, 80, 18],
    backdrop_path: "/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg",
    adult: false,
    overview:
      "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
    poster_path: "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
    popularity: 98.917,
    media_type: "movie",
  },
  {
    id: 556678,
    video: false,
    vote_count: 382,
    vote_average: 7,
    title: "Emma.",
    release_date: "2020-02-13",
    original_language: "en",
    original_title: "Emma.",
    genre_ids: [35, 18, 10749],
    backdrop_path: "/5GbkL9DDRzq3A21nR7Gkv6cFGjq.jpg",
    adult: false,
    overview:
      "In 1800s England, a well-meaning but selfish young woman meddles in the love lives of her friends.",
    poster_path: "/uHpHzbHLSsVmAuuGuQSpyVDZmDc.jpg",
    popularity: 41.656,
    media_type: "movie",
  },
  {
    id: 531876,
    video: false,
    vote_count: 126,
    vote_average: 7,
    title: "The Outpost",
    release_date: "2020-06-24",
    original_language: "en",
    original_title: "The Outpost",
    genre_ids: [28, 18, 36, 10752],
    backdrop_path: "/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg",
    adult: false,
    overview:
      "A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.",
    poster_path: "/hPkqY2EMqWUnFEoedukilIUieVG.jpg",
    popularity: 117.321,
    media_type: "movie",
  },
  {
    id: 686245,
    video: false,
    vote_count: 11,
    vote_average: 5.2,
    title: "Survive the Night",
    release_date: "2020-07-09",
    original_language: "en",
    original_title: "Survive the Night",
    genre_ids: [28, 53],
    backdrop_path: "/cVnCwyaKP7exbgaCMR9DJS4xleZ.jpg",
    adult: false,
    overview:
      "A disgraced doctor and his family are held hostage at their home by criminals on the run, when a robbery-gone-awry requires them to seek immediate medical attention.",
    poster_path: "/niyXFhGIk4W2WTcX2Eod8vx2Mfe.jpg",
    popularity: 48.775,
    media_type: "movie",
  },
  {
    id: 428045,
    video: false,
    vote_count: 99,
    vote_average: 5.9,
    title: "Journey to China: The Mystery of Iron Mask",
    release_date: "2019-08-16",
    original_language: "ru",
    original_title: "Тайна Печати дракона",
    genre_ids: [12, 14],
    backdrop_path: "/5yiCqzmxYv36GGdc05egCMHedbX.jpg",
    adult: false,
    overview:
      "The Russian Czar Peter the Great commissions Jonathan Green, an English traveller, to map the Far East territories of the Russian Empire. Green sets off on yet another long journey, full of unbelievable adventures, which eventually leads him to China. On his way, the famous cartographer makes breath-taking discoveries, meets mysterious creatures, Chinese princesses, deadly masters of oriental martial arts, and even Lun Van, the King of Dragons, himself. What could be more perilous than looking into the eyes of Viy? Only meeting him again… What will prevail this time — the unflinching scepticism of the scientist or ancient black magic, which has already gained influence over the Far East Lands?",
    poster_path: "/GAeK18hkfR6rzlo1vITvQhoEiW.jpg",
    popularity: 76.241,
    media_type: "movie",
  },
  {
    id: 451184,
    video: false,
    vote_count: 107,
    vote_average: 6.3,
    title: "Wasp Network",
    release_date: "2020-01-29",
    original_language: "en",
    original_title: "Wasp Network",
    genre_ids: [18, 36, 53],
    backdrop_path: "/72r4uAQGsa8KEv0DB2TpSu31lEB.jpg",
    adult: false,
    overview:
      "Havana, Cuba, 1990. René González, an airplane pilot, unexpectedly flees the country, leaving behind his wife Olga and his daughter Irma, and begins a new life in Miami, where he becomes a member of an anti-Castro organization.",
    poster_path: "/fOvqEunubL3wPskvtk2Ficfl0pH.jpg",
    popularity: 54.082,
    media_type: "movie",
  },
  {
    id: 508439,
    video: false,
    vote_count: 2522,
    vote_average: 7.9,
    title: "Onward",
    release_date: "2020-02-29",
    original_language: "en",
    original_title: "Onward",
    genre_ids: [12, 16, 35, 14, 10751],
    backdrop_path: "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
    adult: false,
    overview:
      "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
    poster_path: "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
    popularity: 67.737,
    media_type: "movie",
  },
  {
    id: 181812,
    video: false,
    vote_count: 5205,
    vote_average: 6.6,
    title: "Star Wars: The Rise of Skywalker",
    release_date: "2019-12-18",
    original_language: "en",
    original_title: "Star Wars: The Rise of Skywalker",
    genre_ids: [28, 12, 878],
    backdrop_path: "/SPkEiZGxq5aHWQ2Zw7AITwSEo2.jpg",
    adult: false,
    overview:
      "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
    poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
    popularity: 63.217,
    media_type: "movie",
  },
  {
    id: 706510,
    video: false,
    vote_count: 162,
    vote_average: 6.5,
    title: "Desperados",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Desperados",
    genre_ids: [35, 10749],
    backdrop_path: "/k8H6Qp4uJ9WHArPQwDqCaW9g3Sj.jpg",
    adult: false,
    overview:
      "A panicked young woman and her two best friends fly to Mexico to delete a ranting email she sent to her new boyfriend. On arrival, they run into her former beau, who soon gets caught up in their frantic scheme.",
    poster_path: "/hoUzSMxGu4Bm73EvH6B3iceFwW8.jpg",
    popularity: 76.859,
    media_type: "movie",
  },
  {
    id: 522627,
    video: false,
    vote_count: 1599,
    vote_average: 7.7,
    title: "The Gentlemen",
    release_date: "2020-01-01",
    original_language: "en",
    original_title: "The Gentlemen",
    genre_ids: [28, 35, 80],
    backdrop_path: "/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg",
    adult: false,
    overview:
      "American expat Mickey Pearson has built a highly profitable marijuana empire in London. When word gets out that he’s looking to cash out of the business forever it triggers plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
    poster_path: "/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg",
    popularity: 53.234,
    media_type: "movie",
  },
];

export const dummyTvShows: TvShowItemAttr[] = [
  {
    original_name: "Oscuro Deseo",
    id: 105214,
    name: "Dark Desire",
    vote_count: 0,
    vote_average: 0,
    first_air_date: "2020-07-15",
    poster_path: "/uxFNAo2A6ZRcgNASLk02hJUbybn.jpg",
    genre_ids: [18, 9648],
    original_language: "es",
    backdrop_path: "/vmVeGFUTXEKwAUpFH9bZwow9zIk.jpg",
    overview:
      "Married Alma spends a fateful weekend away from home that ignites passion, ends in tragedy and leads her to question the truth about those close to her.",
    origin_country: ["MX"],
    popularity: 38.622,
    media_type: "tv",
  },
  {
    original_name: "Brave New World",
    id: 93289,
    name: "Brave New World",
    vote_count: 3,
    vote_average: 4.7,
    first_air_date: "2020-07-15",
    poster_path: "/fX5vqZfEIkV5QZbi8McTh40QhdW.jpg",
    genre_ids: [18, 10765],
    original_language: "en",
    backdrop_path: "/wQ6QDv5mX3IOQq7pWpFZBOp9CPC.jpg",
    overview:
      "In a utopia whose perfection hinges upon control of monogamy and privacy, members of the collective begin to question the rules, putting their regimented society on a collision course with forbidden love and revolution.",
    origin_country: ["US"],
    popularity: 49.92,
    media_type: "tv",
  },
  {
    original_name: "Snowpiercer",
    id: 79680,
    name: "Snowpiercer",
    vote_count: 231,
    vote_average: 7.6,
    first_air_date: "2020-05-17",
    poster_path: "/n6UNHZoiYj81abwmG38HbNjflDx.jpg",
    genre_ids: [10765],
    original_language: "en",
    backdrop_path: "/dJBKKbrQIqcQ9EUbdM48dM8mso6.jpg",
    overview:
      "Set more than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.",
    origin_country: ["US"],
    popularity: 80.289,
    media_type: "tv",
  },
  {
    original_name: "The 100",
    id: 48866,
    name: "The 100",
    vote_count: 3474,
    vote_average: 7.6,
    first_air_date: "2014-03-19",
    poster_path: "/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg",
    genre_ids: [18, 10759, 10765],
    original_language: "en",
    backdrop_path: "/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg",
    overview:
      "100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
    origin_country: ["US"],
    popularity: 105.046,
    media_type: "tv",
  },
  {
    original_name: "The Business of Drugs",
    id: 105305,
    name: "The Business of Drugs",
    vote_count: 1,
    vote_average: 9,
    first_air_date: "2020-07-14",
    poster_path: "/blyObONhcnleib1xqcwS9uvAfIM.jpg",
    genre_ids: [80, 99],
    original_language: "en",
    backdrop_path: "/54f4FsZ4248sCrvzQnw6XXTFWWY.jpg",
    overview:
      "To detail how drugs push people into risky — even deadly — behaviors, a former CIA analyst investigates the economics of six illicit substances.",
    origin_country: [],
    popularity: 37.185,
    media_type: "tv",
  },
  {
    original_name: "Dark",
    id: 70523,
    name: "Dark",
    vote_count: 2624,
    vote_average: 8.5,
    first_air_date: "2017-12-01",
    poster_path: "/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    genre_ids: [80, 18, 9648, 10765],
    original_language: "de",
    backdrop_path: "/3lBDg3i6nn5R2NKFCJ6oKyUo2j5.jpg",
    overview:
      "A missing child causes four families to help each other for answers. What they could not imagine is that this mystery would be connected to innumerable other secrets of the small town.",
    origin_country: ["DE"],
    popularity: 107.397,
    media_type: "tv",
  },
  {
    original_name: "P-Valley",
    id: 87017,
    name: "P-Valley",
    vote_count: 9,
    vote_average: 7.9,
    first_air_date: "2020-07-12",
    poster_path: "/ix4IFXguK5TP0lSEPcqbDU0XWsA.jpg",
    genre_ids: [18],
    original_language: "en",
    backdrop_path: "/acXcWi3o5HivpPHPEcrHv3eIlg7.jpg",
    overview:
      "Down deep in the Mississippi Delta, Trap music meets film noir in this kaleidoscopic story of a little-strip-club-that-could and the big characters who come through its doors—the hopeful, the lost, the broken, the ballers, the beautiful, and the damned.",
    origin_country: ["US"],
    popularity: 37.827,
    media_type: "tv",
  },
  {
    original_name: "Game of Thrones",
    id: 1399,
    name: "Game of Thrones",
    vote_count: 9176,
    vote_average: 8.3,
    first_air_date: "2011-04-17",
    poster_path: "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    genre_ids: [18, 10765],
    original_language: "en",
    backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    origin_country: ["US"],
    popularity: 94.175,
    media_type: "tv",
  },
  {
    original_name: "Marvel's Agents of S.H.I.E.L.D.",
    id: 1403,
    name: "Marvel's Agents of S.H.I.E.L.D.",
    vote_count: 1831,
    vote_average: 7.1,
    first_air_date: "2013-09-24",
    poster_path: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    genre_ids: [18, 10759, 10765],
    original_language: "en",
    backdrop_path: "/mUCV0W6TaAk8UWA5yAmqCywC63F.jpg",
    overview:
      "Agent Phil Coulson of S.H.I.E.L.D. (Strategic Homeland Intervention, Enforcement and Logistics Division) puts together a team of agents to investigate the new, the strange and the unknown around the globe, protecting the ordinary from the extraordinary.",
    origin_country: ["US"],
    popularity: 116.459,
    media_type: "tv",
  },
  {
    backdrop_path: "/ykK9VfewaHyzqUSbiSPKFKfPfk.jpg",
    first_air_date: "2020-07-15",
    genre_ids: [16, 10759],
    id: 94388,
    name: "Gibiate",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "ジビエート",
    overview:
      "In 2030, Japan. A virus has infected humans throughout the world. Infected people turn into different forms of monsters based on their ages, sexes and races. The virus is named 'Gibia' - after being rich in variety like gibia. Just then, a pair of samurai and ninja appeared in such a blighted wasteland of Japan. They both traveled from the early Edo period, fighting together with help from a doctor who tries to find cure for Gibia. Facing ceaseless attacks from Gibias, and outlaws that attack travelers for food, they start the dangerous journey with enemies all around.",
    poster_path: "/6AaCfEMkJlKxiFLchVmhJi7eDzb.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 32.262,
    media_type: "tv",
  },
  {
    original_name: "Stargirl",
    id: 80986,
    name: "Stargirl",
    vote_count: 427,
    vote_average: 7.9,
    first_air_date: "2020-05-18",
    poster_path: "/sWSGc3Bb7aCTOPvAIkkhqI7ae9H.jpg",
    genre_ids: [80, 18, 10759, 10765],
    original_language: "en",
    backdrop_path: "/b5lKppEquuQWm6fTjGcu2g8FJgs.jpg",
    overview:
      'Courtney Whitmore, a smart, athletic and above all else kind girl, discovers her step-father has a secret: he used to be the sidekick to a superhero. "Borrowing" the long-lost hero’s cosmic staff, she becomes the unlikely inspiration for an entirely new generation of superheroes.',
    origin_country: ["US"],
    popularity: 48.493,
    media_type: "tv",
  },
  {
    original_name: "Warrior Nun",
    id: 87689,
    name: "Warrior Nun",
    vote_count: 197,
    vote_average: 8.1,
    first_air_date: "2020-07-02",
    poster_path: "/77OM9jMJ8nglaolHLwrAW7kvadV.jpg",
    genre_ids: [18, 10759, 10765],
    original_language: "en",
    backdrop_path: "/u2R4WKNvEQAfgiEl6kAOvj6AuFv.jpg",
    overview:
      "After waking up in a morgue, an orphaned teen discovers she now possesses superpowers as the chosen Halo-Bearer for a secret sect of demon-hunting nuns.",
    origin_country: ["US"],
    popularity: 55.293,
    media_type: "tv",
  },
  {
    original_name: "Perry Mason",
    id: 85853,
    name: "Perry Mason",
    vote_count: 55,
    vote_average: 7.2,
    first_air_date: "2020-06-21",
    poster_path: "/gPBf35AqvXHvKEpDHaQ4D9xXxeX.jpg",
    genre_ids: [80, 18, 9648],
    original_language: "en",
    backdrop_path: "/jGwCKq2EbQbsgNTBM2NoEzFHRdh.jpg",
    overview:
      "Set in 1932 Los Angeles, the series focuses on the origin story of famed defense lawyer Perry Mason. Living check-to-check as a low-rent private investigator, Mason is haunted by his wartime experiences in France and suffering the effects of a broken marriage. L.A. is booming while the rest of the country recovers from the Great Depression — but a kidnapping gone very wrong leads to Mason exposing a fractured city as he uncovers the truth of the crime.",
    origin_country: ["US"],
    popularity: 33.934,
    media_type: "tv",
  },
  {
    original_name: "La casa de papel",
    id: 71446,
    name: "Money Heist",
    vote_count: 7590,
    vote_average: 8.4,
    first_air_date: "2017-05-02",
    poster_path: "/MoEKaPFHABtA1xKoOteirGaHl1.jpg",
    genre_ids: [80, 18],
    original_language: "es",
    backdrop_path: "/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    origin_country: ["ES"],
    popularity: 53.974,
    media_type: "tv",
  },
  {
    original_name: "Condor",
    id: 71146,
    name: "Condor",
    vote_count: 77,
    vote_average: 6.6,
    first_air_date: "2018-06-06",
    poster_path: "/28cIK70tN2t4gPTV8CBQZED1H2G.jpg",
    genre_ids: [18],
    original_language: "en",
    backdrop_path: "/fc9ebsTmVCvv6jjD2qT7rWazaej.jpg",
    overview:
      "Young CIA analyst Joe Turner has his idealism tested when he learns that the CIA has been using an algorithm he developed to spy on American citizens, leading the organization to a terrorist plot that threatens the lives of millions.  Inspired by Sydney Pollack’s 1975 political thriller Three Days of the Condor.",
    origin_country: ["US"],
    popularity: 34.344,
    media_type: "tv",
  },
  {
    original_name: "Yellowstone",
    id: 73586,
    name: "Yellowstone",
    vote_count: 109,
    vote_average: 7.8,
    first_air_date: "2018-06-20",
    poster_path: "/43nVQqVsrshaOx9GfJq6JstsfCX.jpg",
    genre_ids: [18, 37],
    original_language: "en",
    backdrop_path: "/oBilGalyrQJTtDuYIljRQGNXXb8.jpg",
    overview:
      "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
    origin_country: ["US"],
    popularity: 37.438,
    media_type: "tv",
  },
  {
    original_name: "사이코지만 괜찮아",
    id: 96462,
    name: "It's Okay to Not Be Okay",
    vote_count: 10,
    vote_average: 9.3,
    first_air_date: "2020-06-20",
    poster_path: "/vBaLz8kZNXYvTjHwrTewkTw3l7k.jpg",
    genre_ids: [35, 18],
    original_language: "ko",
    backdrop_path: "/qOQFBEbNqDu7tmfL9wKMc8ECW3L.jpg",
    overview:
      "Desperate to escape from his emotional baggage and the heavy responsibility he’s had all his life, a psychiatric ward worker begins to heal with help from the unexpected—a woman who writes fairy tales but doesn’t believe in them.",
    origin_country: ["KR"],
    popularity: 14.747,
    media_type: "tv",
  },
  {
    original_name: "United We Fall",
    id: 92153,
    name: "United We Fall",
    vote_count: 2,
    vote_average: 7,
    first_air_date: "2020-07-15",
    poster_path: "/kWDLbp2J1JoZUo6PsZl7TOPpo1Y.jpg",
    genre_ids: [35],
    original_language: "en",
    backdrop_path: "/kWhiFPoEIBG0YUk2raneMHYyOPf.jpg",
    overview:
      "The trials and tribulations of Jo and Bill, parents of two young kids, as they try to make it day to day as a functioning family. Bill’s very judgmental live-in mother and Jo’s large, Latinx Catholic family will never hesitate to let our couple know they’re seemingly screwing up, but Bill and Jo will always have each other’s backs, united against everyone – other parents, teachers, doctors, specialists, coaches, co-workers and, especially, their kids.",
    origin_country: ["US"],
    popularity: 36.72,
    media_type: "tv",
  },
  {
    original_name: "Absentia",
    id: 72755,
    name: "Absentia",
    vote_count: 77,
    vote_average: 7.1,
    first_air_date: "2017-09-25",
    poster_path: "/uy236cUbjkG0ncSmNeMz2f2OO9Q.jpg",
    genre_ids: [80, 18, 9648],
    original_language: "en",
    backdrop_path: "/OwDuNYVpVsC4kBcGvniaEraUM7.jpg",
    overview:
      "A missing FBI agent reappears six years after being declared dead.",
    origin_country: ["US"],
    popularity: 56.337,
    media_type: "tv",
  },
  {
    original_name: "Little Voice",
    id: 103783,
    name: "Little Voice",
    vote_count: 5,
    vote_average: 8,
    first_air_date: "2020-07-10",
    poster_path: "/vxzWAyNw7T7r7a6aQdPe2bahMPh.jpg",
    genre_ids: [35, 18],
    original_language: "en",
    backdrop_path: "/wRDOlYGIEqeupAaggkMfjiuib1j.jpg",
    overview:
      "A love letter to the diverse musicality of New York and an exploration the universal journey of finding your authentic voice in your early 20s — and the courage to use it.",
    origin_country: ["US"],
    popularity: 23.874,
    media_type: "tv",
  },
];
