import {
  MovieItemAttr,
  TvShowItemAttr,
  PersonItemAttr,
} from "../../components/Section/types";

export const dummyMovies: MovieItemAttr[] = [
  {
    id: 547016,
    video: false,
    vote_count: 669,
    vote_average: 7.3,
    title: "The Old Guard",
    release_date: "2020-07-10",
    original_language: "en",
    original_title: "The Old Guard",
    genre_ids: [28, 14],
    backdrop_path: "/m0ObOaJBerZ3Unc74l471ar8Iiy.jpg",
    adult: false,
    overview:
      "Four undying warriors who've secretly protected humanity for centuries become targeted for their mysterious powers just as they discover a new immortal.",
    poster_path: "/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg",
    popularity: 351.438,
    media_type: "movie",
  },
  {
    id: 516486,
    video: false,
    vote_count: 148,
    vote_average: 7,
    title: "Greyhound",
    release_date: "2020-07-10",
    original_language: "en",
    original_title: "Greyhound",
    genre_ids: [28, 18, 10752],
    backdrop_path: "/xXBnM6uSTk6qqCf0SRZKXcga9Ba.jpg",
    adult: false,
    overview:
      "A first-time captain leads a convoy of allied ships carrying thousands of soldiers across the treacherous waters of the “Black Pit” to the front lines of WW2. With no air cover protection for 5 days, the captain and his convoy must battle the surrounding enemy Nazi U-boats in order to give the allies a chance to win the war.",
    poster_path: "/AsdB9A2XGalCZVjlyG9tRf03IfW.jpg",
    popularity: 351.193,
    media_type: "movie",
  },
  {
    id: 587792,
    video: false,
    vote_count: 105,
    vote_average: 7.9,
    title: "Palm Springs",
    release_date: "2020-01-26",
    original_language: "en",
    original_title: "Palm Springs",
    genre_ids: [35, 878, 10749],
    backdrop_path: "/d7JUXVvjvVCXWs1mlpyO5ESdWdT.jpg",
    adult: false,
    overview:
      "When carefree Nyles and reluctant maid of honor Sarah have a chance encounter at a Palm Springs wedding, things get complicated as they are unable to escape the venue, themselves, or each other.",
    poster_path: "/yf5IuMW6GHghu39kxA0oFx7Bxmj.jpg",
    popularity: 66.585,
    media_type: "movie",
  },
  {
    id: 299534,
    video: false,
    vote_count: 14114,
    vote_average: 8.3,
    title: "Avengers: Endgame",
    release_date: "2019-04-24",
    original_language: "en",
    original_title: "Avengers: Endgame",
    genre_ids: [28, 12, 878],
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    adult: false,
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    popularity: 72.622,
    media_type: "movie",
  },
  {
    id: 539181,
    video: false,
    vote_count: 32,
    vote_average: 6.6,
    title: "Relic",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Relic",
    genre_ids: [18, 27],
    backdrop_path: "/vpUUznNzW85xo02H16RaSxRNS1.jpg",
    adult: false,
    overview:
      "When Edna, the elderly and widowed matriarch of the family, goes missing, her daughter Kay and granddaughter Sam travel to their remote family home to find her. Soon after her return, they start to discover a sinister presence haunting the house and taking control of Edna.",
    poster_path: "/3wZ0gxLqsPleneFSTZILmM3BE8Q.jpg",
    popularity: 87.111,
    media_type: "movie",
  },
  {
    id: 606234,
    video: false,
    vote_count: 7,
    vote_average: 8.4,
    title: "Archive",
    release_date: "2020-07-01",
    original_language: "en",
    original_title: "Archive",
    genre_ids: [878],
    backdrop_path: "/ckRBJIHrUhQMMkEhuk4iW2NIBWP.jpg",
    adult: false,
    overview:
      "2038: George Almore is working on a true human-equivalent AI, and his latest prototype is almost ready. This sensitive phase is also the riskiest as he has a goal that must be hidden at all costs—being reunited with his dead wife.",
    poster_path: "/q9t1AxbzyGQENDunK1GT8OS4aJl.jpg",
    popularity: 53.994,
    media_type: "movie",
  },
  {
    id: 556574,
    video: false,
    vote_count: 220,
    vote_average: 8.6,
    title: "Hamilton",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Hamilton",
    genre_ids: [18, 36, 10402],
    backdrop_path: "/uWVkEo9PWHu9algZsiLPi6sRU64.jpg",
    adult: false,
    overview:
      "Presenting the tale of American founding father Alexander Hamilton, this filmed version of the original Broadway smash hit is the story of America then, told by America now.",
    poster_path: "/h1B7tW0t399VDjAcWJh8m87469b.jpg",
    popularity: 82.625,
    media_type: "movie",
  },
  {
    id: 385103,
    video: false,
    vote_count: 1226,
    vote_average: 8,
    title: "Scoob!",
    release_date: "2020-05-15",
    original_language: "en",
    original_title: "Scoob!",
    genre_ids: [12, 16, 35, 9648, 10751],
    backdrop_path: "/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg",
    adult: false,
    overview:
      "In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.",
    poster_path: "/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg",
    popularity: 100.079,
    media_type: "movie",
  },
  {
    id: 11,
    video: false,
    vote_count: 13945,
    vote_average: 8.2,
    title: "Star Wars",
    release_date: "1977-05-25",
    original_language: "en",
    original_title: "Star Wars",
    genre_ids: [28, 12, 878],
    backdrop_path: "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
    adult: false,
    overview:
      "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
    poster_path: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    popularity: 68.052,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/yOBBzBlN72C6QLtXaskQ87fdVkS.jpg",
    genre_ids: [28, 12, 36],
    id: 635237,
    original_language: "fr",
    original_title: "Arthur & Merlin: Knights of Camelot",
    overview:
      "King Arthur returns home after fighting the Roman Empire. His illegitimate son has corrupted the throne of Camelot and King Arthur must reunite with the wizard Merlin and the Knights of the Round Table to fight to get back his crown.",
    poster_path: "/chGTXsvn53XvEnvsJ9ZD9eiYKx9.jpg",
    release_date: "2020-05-28",
    title: "Arthur & Merlin: Knights of Camelot",
    video: false,
    vote_average: 2.1,
    vote_count: 8,
    popularity: 4.74,
    media_type: "movie",
  },
  {
    id: 495764,
    video: false,
    vote_count: 4953,
    vote_average: 7.2,
    title:
      "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
    release_date: "2020-02-05",
    original_language: "en",
    original_title:
      "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
    genre_ids: [28, 35, 80, 18],
    backdrop_path: "/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg",
    adult: false,
    overview:
      "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
    poster_path: "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
    popularity: 98.917,
    media_type: "movie",
  },
  {
    id: 556678,
    video: false,
    vote_count: 382,
    vote_average: 7,
    title: "Emma.",
    release_date: "2020-02-13",
    original_language: "en",
    original_title: "Emma.",
    genre_ids: [35, 18, 10749],
    backdrop_path: "/5GbkL9DDRzq3A21nR7Gkv6cFGjq.jpg",
    adult: false,
    overview:
      "In 1800s England, a well-meaning but selfish young woman meddles in the love lives of her friends.",
    poster_path: "/uHpHzbHLSsVmAuuGuQSpyVDZmDc.jpg",
    popularity: 41.656,
    media_type: "movie",
  },
  {
    id: 531876,
    video: false,
    vote_count: 126,
    vote_average: 7,
    title: "The Outpost",
    release_date: "2020-06-24",
    original_language: "en",
    original_title: "The Outpost",
    genre_ids: [28, 18, 36, 10752],
    backdrop_path: "/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg",
    adult: false,
    overview:
      "A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.",
    poster_path: "/hPkqY2EMqWUnFEoedukilIUieVG.jpg",
    popularity: 117.321,
    media_type: "movie",
  },
  {
    id: 686245,
    video: false,
    vote_count: 11,
    vote_average: 5.2,
    title: "Survive the Night",
    release_date: "2020-07-09",
    original_language: "en",
    original_title: "Survive the Night",
    genre_ids: [28, 53],
    backdrop_path: "/cVnCwyaKP7exbgaCMR9DJS4xleZ.jpg",
    adult: false,
    overview:
      "A disgraced doctor and his family are held hostage at their home by criminals on the run, when a robbery-gone-awry requires them to seek immediate medical attention.",
    poster_path: "/niyXFhGIk4W2WTcX2Eod8vx2Mfe.jpg",
    popularity: 48.775,
    media_type: "movie",
  },
  {
    id: 428045,
    video: false,
    vote_count: 99,
    vote_average: 5.9,
    title: "Journey to China: The Mystery of Iron Mask",
    release_date: "2019-08-16",
    original_language: "ru",
    original_title: "Тайна Печати дракона",
    genre_ids: [12, 14],
    backdrop_path: "/5yiCqzmxYv36GGdc05egCMHedbX.jpg",
    adult: false,
    overview:
      "The Russian Czar Peter the Great commissions Jonathan Green, an English traveller, to map the Far East territories of the Russian Empire. Green sets off on yet another long journey, full of unbelievable adventures, which eventually leads him to China. On his way, the famous cartographer makes breath-taking discoveries, meets mysterious creatures, Chinese princesses, deadly masters of oriental martial arts, and even Lun Van, the King of Dragons, himself. What could be more perilous than looking into the eyes of Viy? Only meeting him again… What will prevail this time — the unflinching scepticism of the scientist or ancient black magic, which has already gained influence over the Far East Lands?",
    poster_path: "/GAeK18hkfR6rzlo1vITvQhoEiW.jpg",
    popularity: 76.241,
    media_type: "movie",
  },
  {
    id: 451184,
    video: false,
    vote_count: 107,
    vote_average: 6.3,
    title: "Wasp Network",
    release_date: "2020-01-29",
    original_language: "en",
    original_title: "Wasp Network",
    genre_ids: [18, 36, 53],
    backdrop_path: "/72r4uAQGsa8KEv0DB2TpSu31lEB.jpg",
    adult: false,
    overview:
      "Havana, Cuba, 1990. René González, an airplane pilot, unexpectedly flees the country, leaving behind his wife Olga and his daughter Irma, and begins a new life in Miami, where he becomes a member of an anti-Castro organization.",
    poster_path: "/fOvqEunubL3wPskvtk2Ficfl0pH.jpg",
    popularity: 54.082,
    media_type: "movie",
  },
  {
    id: 508439,
    video: false,
    vote_count: 2522,
    vote_average: 7.9,
    title: "Onward",
    release_date: "2020-02-29",
    original_language: "en",
    original_title: "Onward",
    genre_ids: [12, 16, 35, 14, 10751],
    backdrop_path: "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
    adult: false,
    overview:
      "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
    poster_path: "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
    popularity: 67.737,
    media_type: "movie",
  },
  {
    id: 181812,
    video: false,
    vote_count: 5205,
    vote_average: 6.6,
    title: "Star Wars: The Rise of Skywalker",
    release_date: "2019-12-18",
    original_language: "en",
    original_title: "Star Wars: The Rise of Skywalker",
    genre_ids: [28, 12, 878],
    backdrop_path: "/SPkEiZGxq5aHWQ2Zw7AITwSEo2.jpg",
    adult: false,
    overview:
      "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
    poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
    popularity: 63.217,
    media_type: "movie",
  },
  {
    id: 706510,
    video: false,
    vote_count: 162,
    vote_average: 6.5,
    title: "Desperados",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Desperados",
    genre_ids: [35, 10749],
    backdrop_path: "/k8H6Qp4uJ9WHArPQwDqCaW9g3Sj.jpg",
    adult: false,
    overview:
      "A panicked young woman and her two best friends fly to Mexico to delete a ranting email she sent to her new boyfriend. On arrival, they run into her former beau, who soon gets caught up in their frantic scheme.",
    poster_path: "/hoUzSMxGu4Bm73EvH6B3iceFwW8.jpg",
    popularity: 76.859,
    media_type: "movie",
  },
  {
    id: 522627,
    video: false,
    vote_count: 1599,
    vote_average: 7.7,
    title: "The Gentlemen",
    release_date: "2020-01-01",
    original_language: "en",
    original_title: "The Gentlemen",
    genre_ids: [28, 35, 80],
    backdrop_path: "/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg",
    adult: false,
    overview:
      "American expat Mickey Pearson has built a highly profitable marijuana empire in London. When word gets out that he’s looking to cash out of the business forever it triggers plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
    poster_path: "/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg",
    popularity: 53.234,
    media_type: "movie",
  },
];

export const dummyTvShows: TvShowItemAttr[] = [
  {
    original_name: "Oscuro Deseo",
    id: 105214,
    name: "Dark Desire",
    vote_count: 0,
    vote_average: 0,
    first_air_date: "2020-07-15",
    poster_path: "/uxFNAo2A6ZRcgNASLk02hJUbybn.jpg",
    genre_ids: [18, 9648],
    original_language: "es",
    backdrop_path: "/vmVeGFUTXEKwAUpFH9bZwow9zIk.jpg",
    overview:
      "Married Alma spends a fateful weekend away from home that ignites passion, ends in tragedy and leads her to question the truth about those close to her.",
    origin_country: ["MX"],
    popularity: 38.622,
    media_type: "tv",
  },
  {
    original_name: "Brave New World",
    id: 93289,
    name: "Brave New World",
    vote_count: 3,
    vote_average: 4.7,
    first_air_date: "2020-07-15",
    poster_path: "/fX5vqZfEIkV5QZbi8McTh40QhdW.jpg",
    genre_ids: [18, 10765],
    original_language: "en",
    backdrop_path: "/wQ6QDv5mX3IOQq7pWpFZBOp9CPC.jpg",
    overview:
      "In a utopia whose perfection hinges upon control of monogamy and privacy, members of the collective begin to question the rules, putting their regimented society on a collision course with forbidden love and revolution.",
    origin_country: ["US"],
    popularity: 49.92,
    media_type: "tv",
  },
  {
    original_name: "Snowpiercer",
    id: 79680,
    name: "Snowpiercer",
    vote_count: 231,
    vote_average: 7.6,
    first_air_date: "2020-05-17",
    poster_path: "/n6UNHZoiYj81abwmG38HbNjflDx.jpg",
    genre_ids: [10765],
    original_language: "en",
    backdrop_path: "/dJBKKbrQIqcQ9EUbdM48dM8mso6.jpg",
    overview:
      "Set more than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.",
    origin_country: ["US"],
    popularity: 80.289,
    media_type: "tv",
  },
  {
    original_name: "The 100",
    id: 48866,
    name: "The 100",
    vote_count: 3474,
    vote_average: 7.6,
    first_air_date: "2014-03-19",
    poster_path: "/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg",
    genre_ids: [18, 10759, 10765],
    original_language: "en",
    backdrop_path: "/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg",
    overview:
      "100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
    origin_country: ["US"],
    popularity: 105.046,
    media_type: "tv",
  },
  {
    original_name: "The Business of Drugs",
    id: 105305,
    name: "The Business of Drugs",
    vote_count: 1,
    vote_average: 9,
    first_air_date: "2020-07-14",
    poster_path: "/blyObONhcnleib1xqcwS9uvAfIM.jpg",
    genre_ids: [80, 99],
    original_language: "en",
    backdrop_path: "/54f4FsZ4248sCrvzQnw6XXTFWWY.jpg",
    overview:
      "To detail how drugs push people into risky — even deadly — behaviors, a former CIA analyst investigates the economics of six illicit substances.",
    origin_country: [],
    popularity: 37.185,
    media_type: "tv",
  },
  {
    original_name: "Dark",
    id: 70523,
    name: "Dark",
    vote_count: 2624,
    vote_average: 8.5,
    first_air_date: "2017-12-01",
    poster_path: "/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    genre_ids: [80, 18, 9648, 10765],
    original_language: "de",
    backdrop_path: "/3lBDg3i6nn5R2NKFCJ6oKyUo2j5.jpg",
    overview:
      "A missing child causes four families to help each other for answers. What they could not imagine is that this mystery would be connected to innumerable other secrets of the small town.",
    origin_country: ["DE"],
    popularity: 107.397,
    media_type: "tv",
  },
  {
    original_name: "P-Valley",
    id: 87017,
    name: "P-Valley",
    vote_count: 9,
    vote_average: 7.9,
    first_air_date: "2020-07-12",
    poster_path: "/ix4IFXguK5TP0lSEPcqbDU0XWsA.jpg",
    genre_ids: [18],
    original_language: "en",
    backdrop_path: "/acXcWi3o5HivpPHPEcrHv3eIlg7.jpg",
    overview:
      "Down deep in the Mississippi Delta, Trap music meets film noir in this kaleidoscopic story of a little-strip-club-that-could and the big characters who come through its doors—the hopeful, the lost, the broken, the ballers, the beautiful, and the damned.",
    origin_country: ["US"],
    popularity: 37.827,
    media_type: "tv",
  },
  {
    original_name: "Game of Thrones",
    id: 1399,
    name: "Game of Thrones",
    vote_count: 9176,
    vote_average: 8.3,
    first_air_date: "2011-04-17",
    poster_path: "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    genre_ids: [18, 10765],
    original_language: "en",
    backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    origin_country: ["US"],
    popularity: 94.175,
    media_type: "tv",
  },
  {
    original_name: "Marvel's Agents of S.H.I.E.L.D.",
    id: 1403,
    name: "Marvel's Agents of S.H.I.E.L.D.",
    vote_count: 1831,
    vote_average: 7.1,
    first_air_date: "2013-09-24",
    poster_path: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    genre_ids: [18, 10759, 10765],
    original_language: "en",
    backdrop_path: "/mUCV0W6TaAk8UWA5yAmqCywC63F.jpg",
    overview:
      "Agent Phil Coulson of S.H.I.E.L.D. (Strategic Homeland Intervention, Enforcement and Logistics Division) puts together a team of agents to investigate the new, the strange and the unknown around the globe, protecting the ordinary from the extraordinary.",
    origin_country: ["US"],
    popularity: 116.459,
    media_type: "tv",
  },
  {
    backdrop_path: "/ykK9VfewaHyzqUSbiSPKFKfPfk.jpg",
    first_air_date: "2020-07-15",
    genre_ids: [16, 10759],
    id: 94388,
    name: "Gibiate",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "ジビエート",
    overview:
      "In 2030, Japan. A virus has infected humans throughout the world. Infected people turn into different forms of monsters based on their ages, sexes and races. The virus is named 'Gibia' - after being rich in variety like gibia. Just then, a pair of samurai and ninja appeared in such a blighted wasteland of Japan. They both traveled from the early Edo period, fighting together with help from a doctor who tries to find cure for Gibia. Facing ceaseless attacks from Gibias, and outlaws that attack travelers for food, they start the dangerous journey with enemies all around.",
    poster_path: "/6AaCfEMkJlKxiFLchVmhJi7eDzb.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 32.262,
    media_type: "tv",
  },
  {
    original_name: "Stargirl",
    id: 80986,
    name: "Stargirl",
    vote_count: 427,
    vote_average: 7.9,
    first_air_date: "2020-05-18",
    poster_path: "/sWSGc3Bb7aCTOPvAIkkhqI7ae9H.jpg",
    genre_ids: [80, 18, 10759, 10765],
    original_language: "en",
    backdrop_path: "/b5lKppEquuQWm6fTjGcu2g8FJgs.jpg",
    overview:
      'Courtney Whitmore, a smart, athletic and above all else kind girl, discovers her step-father has a secret: he used to be the sidekick to a superhero. "Borrowing" the long-lost hero’s cosmic staff, she becomes the unlikely inspiration for an entirely new generation of superheroes.',
    origin_country: ["US"],
    popularity: 48.493,
    media_type: "tv",
  },
  {
    original_name: "Warrior Nun",
    id: 87689,
    name: "Warrior Nun",
    vote_count: 197,
    vote_average: 8.1,
    first_air_date: "2020-07-02",
    poster_path: "/77OM9jMJ8nglaolHLwrAW7kvadV.jpg",
    genre_ids: [18, 10759, 10765],
    original_language: "en",
    backdrop_path: "/u2R4WKNvEQAfgiEl6kAOvj6AuFv.jpg",
    overview:
      "After waking up in a morgue, an orphaned teen discovers she now possesses superpowers as the chosen Halo-Bearer for a secret sect of demon-hunting nuns.",
    origin_country: ["US"],
    popularity: 55.293,
    media_type: "tv",
  },
  {
    original_name: "Perry Mason",
    id: 85853,
    name: "Perry Mason",
    vote_count: 55,
    vote_average: 7.2,
    first_air_date: "2020-06-21",
    poster_path: "/gPBf35AqvXHvKEpDHaQ4D9xXxeX.jpg",
    genre_ids: [80, 18, 9648],
    original_language: "en",
    backdrop_path: "/jGwCKq2EbQbsgNTBM2NoEzFHRdh.jpg",
    overview:
      "Set in 1932 Los Angeles, the series focuses on the origin story of famed defense lawyer Perry Mason. Living check-to-check as a low-rent private investigator, Mason is haunted by his wartime experiences in France and suffering the effects of a broken marriage. L.A. is booming while the rest of the country recovers from the Great Depression — but a kidnapping gone very wrong leads to Mason exposing a fractured city as he uncovers the truth of the crime.",
    origin_country: ["US"],
    popularity: 33.934,
    media_type: "tv",
  },
  {
    original_name: "La casa de papel",
    id: 71446,
    name: "Money Heist",
    vote_count: 7590,
    vote_average: 8.4,
    first_air_date: "2017-05-02",
    poster_path: "/MoEKaPFHABtA1xKoOteirGaHl1.jpg",
    genre_ids: [80, 18],
    original_language: "es",
    backdrop_path: "/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    origin_country: ["ES"],
    popularity: 53.974,
    media_type: "tv",
  },
  {
    original_name: "Condor",
    id: 71146,
    name: "Condor",
    vote_count: 77,
    vote_average: 6.6,
    first_air_date: "2018-06-06",
    poster_path: "/28cIK70tN2t4gPTV8CBQZED1H2G.jpg",
    genre_ids: [18],
    original_language: "en",
    backdrop_path: "/fc9ebsTmVCvv6jjD2qT7rWazaej.jpg",
    overview:
      "Young CIA analyst Joe Turner has his idealism tested when he learns that the CIA has been using an algorithm he developed to spy on American citizens, leading the organization to a terrorist plot that threatens the lives of millions.  Inspired by Sydney Pollack’s 1975 political thriller Three Days of the Condor.",
    origin_country: ["US"],
    popularity: 34.344,
    media_type: "tv",
  },
  {
    original_name: "Yellowstone",
    id: 73586,
    name: "Yellowstone",
    vote_count: 109,
    vote_average: 7.8,
    first_air_date: "2018-06-20",
    poster_path: "/43nVQqVsrshaOx9GfJq6JstsfCX.jpg",
    genre_ids: [18, 37],
    original_language: "en",
    backdrop_path: "/oBilGalyrQJTtDuYIljRQGNXXb8.jpg",
    overview:
      "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
    origin_country: ["US"],
    popularity: 37.438,
    media_type: "tv",
  },
  {
    original_name: "사이코지만 괜찮아",
    id: 96462,
    name: "It's Okay to Not Be Okay",
    vote_count: 10,
    vote_average: 9.3,
    first_air_date: "2020-06-20",
    poster_path: "/vBaLz8kZNXYvTjHwrTewkTw3l7k.jpg",
    genre_ids: [35, 18],
    original_language: "ko",
    backdrop_path: "/qOQFBEbNqDu7tmfL9wKMc8ECW3L.jpg",
    overview:
      "Desperate to escape from his emotional baggage and the heavy responsibility he’s had all his life, a psychiatric ward worker begins to heal with help from the unexpected—a woman who writes fairy tales but doesn’t believe in them.",
    origin_country: ["KR"],
    popularity: 14.747,
    media_type: "tv",
  },
  {
    original_name: "United We Fall",
    id: 92153,
    name: "United We Fall",
    vote_count: 2,
    vote_average: 7,
    first_air_date: "2020-07-15",
    poster_path: "/kWDLbp2J1JoZUo6PsZl7TOPpo1Y.jpg",
    genre_ids: [35],
    original_language: "en",
    backdrop_path: "/kWhiFPoEIBG0YUk2raneMHYyOPf.jpg",
    overview:
      "The trials and tribulations of Jo and Bill, parents of two young kids, as they try to make it day to day as a functioning family. Bill’s very judgmental live-in mother and Jo’s large, Latinx Catholic family will never hesitate to let our couple know they’re seemingly screwing up, but Bill and Jo will always have each other’s backs, united against everyone – other parents, teachers, doctors, specialists, coaches, co-workers and, especially, their kids.",
    origin_country: ["US"],
    popularity: 36.72,
    media_type: "tv",
  },
  {
    original_name: "Absentia",
    id: 72755,
    name: "Absentia",
    vote_count: 77,
    vote_average: 7.1,
    first_air_date: "2017-09-25",
    poster_path: "/uy236cUbjkG0ncSmNeMz2f2OO9Q.jpg",
    genre_ids: [80, 18, 9648],
    original_language: "en",
    backdrop_path: "/OwDuNYVpVsC4kBcGvniaEraUM7.jpg",
    overview:
      "A missing FBI agent reappears six years after being declared dead.",
    origin_country: ["US"],
    popularity: 56.337,
    media_type: "tv",
  },
  {
    original_name: "Little Voice",
    id: 103783,
    name: "Little Voice",
    vote_count: 5,
    vote_average: 8,
    first_air_date: "2020-07-10",
    poster_path: "/vxzWAyNw7T7r7a6aQdPe2bahMPh.jpg",
    genre_ids: [35, 18],
    original_language: "en",
    backdrop_path: "/wRDOlYGIEqeupAaggkMfjiuib1j.jpg",
    overview:
      "A love letter to the diverse musicality of New York and an exploration the universal journey of finding your authentic voice in your early 20s — and the courage to use it.",
    origin_country: ["US"],
    popularity: 23.874,
    media_type: "tv",
  },
];

export const dummyPeople: PersonItemAttr[] = [
  {
    adult: false,
    gender: 1,
    name: "Kelly Preston",
    id: 11164,
    known_for: [
      {
        id: 755,
        video: false,
        vote_count: 3841,
        vote_average: 7,
        title: "From Dusk Till Dawn",
        release_date: "1996-01-19",
        original_language: "en",
        original_title: "From Dusk Till Dawn",
        genre_ids: [28, 80, 27, 53],
        backdrop_path: "/yE91pBv4ouDPzNUSLx1pdXSHHrL.jpg",
        adult: false,
        overview:
          "Seth Gecko and his younger brother Richard are on the run after a bloody bank robbery in Texas. They escape across the border into Mexico and will be home-free the next morning, when they pay off the local kingpin. They just have to survive 'from dusk till dawn' at the rendezvous point, which turns out to be a Hell of a strip joint.",
        poster_path: "/sV3kIAmvJ9tPz4Lq5fuf9LLMxte.jpg",
        popularity: 18.455,
        media_type: "movie",
      },
      {
        id: 35690,
        video: false,
        vote_count: 2577,
        vote_average: 7.2,
        title: "The Last Song",
        release_date: "2010-03-31",
        original_language: "en",
        original_title: "The Last Song",
        genre_ids: [18, 10749, 10751],
        backdrop_path: "/hlBsJGliow6OQ1qs1CAhELS0wi1.jpg",
        adult: false,
        overview:
          "A drama centered on a rebellious girl who is sent to a Southern beach town for the summer to stay with her father. Through their mutual love of music, the estranged duo learn to reconnect.",
        poster_path: "/deOzvJHnSSl8FI1HEJjPGgOsS9U.jpg",
        popularity: 20.941,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/n1Gh3MJAVvXmkgSDf3SOLlPCjag.jpg",
        genre_ids: [35, 18, 10749],
        id: 9390,
        original_language: "en",
        original_title: "Jerry Maguire",
        overview:
          "Jerry Maguire used to be a typical sports agent: willing to do just about anything he could to get the biggest possible contracts for his clients, plus a nice commission for himself. Then, one day, he suddenly has second thoughts about what he's really doing. When he voices these doubts, he ends up losing his job and all of his clients, save Rod Tidwell, an egomaniacal football player.",
        poster_path: "/2FJFChUeEgYpCvsLfAMXjcFtFOy.jpg",
        release_date: "1996-12-13",
        title: "Jerry Maguire",
        video: false,
        vote_average: 6.9,
        vote_count: 1983,
        popularity: 21.985,
        media_type: "movie",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/bJ0G5SDuKUnnslQAynnEDRYo1ms.jpg",
    popularity: 9.833,
    media_type: "person",
  },
  {
    known_for_department: "Acting",
    adult: false,
    id: 31,
    profile_path: "/2gY92j2lkNHL2cThBhPmgXLd5PL.jpg",
    name: "Tom Hanks",
    known_for: [
      {
        poster_path: "/clolk7rB5lAjs41SD0Vt6IXYLMm.jpg",
        popularity: 41.202,
        vote_count: 18404,
        video: false,
        media_type: "movie",
        id: 13,
        adult: false,
        backdrop_path: "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg",
        original_language: "en",
        original_title: "Forrest Gump",
        genre_ids: [35, 18, 10749],
        title: "Forrest Gump",
        vote_average: 8.4,
        overview:
          "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
        release_date: "1994-07-06",
      },
      {
        poster_path: "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
        popularity: 40.942,
        vote_count: 12628,
        video: false,
        media_type: "movie",
        id: 862,
        adult: false,
        backdrop_path: "/lxD5ak7BOoinRNehOCA85CQ8ubr.jpg",
        original_language: "en",
        original_title: "Toy Story",
        genre_ids: [16, 35, 10751],
        title: "Toy Story",
        vote_average: 7.9,
        overview:
          "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
        release_date: "1995-10-30",
      },
      {
        poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
        popularity: 40.701,
        vote_count: 10515,
        video: false,
        media_type: "movie",
        id: 497,
        adult: false,
        backdrop_path: "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
        original_language: "en",
        original_title: "The Green Mile",
        genre_ids: [80, 18, 14],
        title: "The Green Mile",
        vote_average: 8.5,
        overview:
          "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        release_date: "1999-12-10",
      },
    ],
    gender: 2,
    popularity: 28.106,
    media_type: "person",
  },
  {
    adult: false,
    gender: 1,
    name: "Naya Rivera",
    id: 158136,
    known_for: [
      {
        original_name: "American Dad!",
        id: 1433,
        name: "American Dad!",
        vote_count: 912,
        vote_average: 6.4,
        first_air_date: "2005-02-06",
        poster_path: "/1aklTBd36LFiFNroOSiherLvLdu.jpg",
        genre_ids: [16, 35],
        original_language: "en",
        backdrop_path: "/2OeS0YPFpqCmi7SA5W6aOPIChc3.jpg",
        overview:
          "The series focuses on an eccentric motley crew that is the Smith family and their three housemates: Father, husband, and breadwinner Stan Smith; his better half housewife, Francine Smith; their college-aged daughter, Hayley Smith; and their high-school-aged son, Steve Smith. Outside of the Smith family, there are three additional main characters, including Hayley's boyfriend turned husband, Jeff Fischer; the family's man-in-a-goldfish-body pet, Klaus; and most notably the family's zany alien, Roger, who is \"full of masquerades, brazenness, and shocking antics.\"",
        origin_country: ["US"],
        popularity: 63.849,
        media_type: "tv",
      },
      {
        backdrop_path: "/byHpstWGQai1p2FpiyUuxLBiPxh.jpg",
        first_air_date: "1990-09-10",
        genre_ids: [35, 10751],
        id: 1892,
        name: "The Fresh Prince of Bel-Air",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Fresh Prince of Bel-Air",
        overview:
          "Will, a street-smart teenager, moves from the tough streets of West Philly to posh Bel-Air to live with his Uncle Philip, Aunt Vivian, his cousins — spoiled Hilary, preppy Carlton and young Ashley — and their sophisticated British butler, Geoffrey. Though Will’s antics and upbringing contrast greatly with the upper-class lifestyle of his extended relatives, he soon finds himself right at home as a loved part of the family.",
        poster_path: "/gYPE5vfStpVTf1ULE11B1Vwm12b.jpg",
        vote_average: 7.8,
        vote_count: 789,
        popularity: 20.502,
        media_type: "tv",
      },
      {
        original_name: "CSI: Miami",
        id: 1620,
        name: "CSI: Miami",
        vote_count: 597,
        vote_average: 7.3,
        first_air_date: "2002-09-23",
        poster_path: "/oWSpWkL57u9PuDkJwV5uyoWMyEb.jpg",
        genre_ids: [80, 18, 9648],
        original_language: "en",
        backdrop_path: "/c1VZ4ZmabAmBrevRGtP9IFKKlhS.jpg",
        overview:
          "CSI: Miami follows Crime Scene Investigators working for the Miami-Dade Police Department as they use physical evidence, similar to their Las Vegas counterparts, to solve grisly murders. The series mixes deduction, gritty subject matter, and character-driven drama in the same vein as the original series in the CSI franchise, except that the Miami CSIs are cops first, scientists second.",
        origin_country: ["US"],
        popularity: 36.148,
        media_type: "tv",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/cqPE62ZqpQ0B6T7pRkB3ZxsS1vZ.jpg",
    popularity: 9.51,
    media_type: "person",
  },
  {
    adult: false,
    gender: 1,
    name: "Charlize Theron",
    id: 6885,
    known_for: [
      {
        id: 76341,
        video: false,
        vote_count: 16657,
        vote_average: 7.5,
        title: "Mad Max: Fury Road",
        release_date: "2015-05-13",
        original_language: "en",
        original_title: "Mad Max: Fury Road",
        genre_ids: [28, 12, 878],
        backdrop_path: "/nlCHUWjY9XWbuEUQauCBgnY8ymF.jpg",
        adult: false,
        overview:
          "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
        poster_path: "/sQuxceRcV3cxKH5CAnAUZe0qFKS.jpg",
        popularity: 29.121,
        media_type: "movie",
      },
      {
        id: 70981,
        video: false,
        vote_count: 8547,
        vote_average: 6.4,
        title: "Prometheus",
        release_date: "2012-05-30",
        original_language: "en",
        original_title: "Prometheus",
        genre_ids: [12, 9648, 878],
        backdrop_path: "/qDG5SlGkWNsjSJWiGTBMFI8DpzA.jpg",
        adult: false,
        overview:
          "A team of explorers discover a clue to the origins of mankind on Earth, leading them on a journey to the darkest corners of the universe. There, they must fight a terrifying battle to save the future of the human race.",
        poster_path: "/qsYQflQhOuhDpQ0W2aOcwqgDAeI.jpg",
        popularity: 30.174,
        media_type: "movie",
      },
      {
        id: 337339,
        video: false,
        vote_count: 7442,
        vote_average: 6.9,
        title: "The Fate of the Furious",
        release_date: "2017-04-12",
        original_language: "en",
        original_title: "The Fate of the Furious",
        genre_ids: [28, 80, 53],
        backdrop_path: "/pEL81RWzS3LaybTCf7vp2KvVLhw.jpg",
        adult: false,
        overview:
          "When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.",
        poster_path: "/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg",
        popularity: 21.288,
        media_type: "movie",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/At0CTQ37ohzX6KgAcZqfhHDZDDX.jpg",
    popularity: 51.561,
    media_type: "person",
  },
  {
    adult: false,
    gender: 2,
    name: "Jeremy Clarkson",
    id: 81113,
    known_for: [
      {
        adult: false,
        backdrop_path: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        genre_ids: [16, 12, 35, 10751],
        id: 920,
        original_language: "en",
        original_title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster_path: "/qa6HCwP4Z15l3hpsASz3auugEW6.jpg",
        release_date: "2006-06-08",
        title: "Cars",
        video: false,
        vote_average: 6.8,
        vote_count: 9566,
        popularity: 22.937,
        media_type: "movie",
      },
      {
        original_name: "Top Gear",
        id: 45,
        name: "Top Gear",
        vote_count: 386,
        vote_average: 7.4,
        first_air_date: "2002-10-20",
        poster_path: "/aqM6QnuhSXzjHlKbXyKUqxaGiWu.jpg",
        genre_ids: [99],
        original_language: "en",
        backdrop_path: "/o8IhJLFGLhqhpgKf68bvts12f5Y.jpg",
        overview:
          "The hosts talk about the latest cars and its specifications. They review the performance of the car and also find out if it is as good as the manufacturers claim. The current hosts are Chris Evans and Matt LeBlanc with The Stig.",
        origin_country: ["GB"],
        popularity: 39.43,
        media_type: "tv",
      },
      {
        original_name: "The Grand Tour",
        id: 67557,
        name: "The Grand Tour",
        vote_count: 354,
        vote_average: 7.8,
        first_air_date: "2016-11-18",
        poster_path: "/4bRY1FiDcLnpwJAELYOLinL3fIp.jpg",
        genre_ids: [99, 10767],
        original_language: "en",
        backdrop_path: "/A2TyMQUlS3HLB7rAdtGn67335XX.jpg",
        overview:
          "Jeremy Clarkson, Richard Hammond and James May are back with a show about adventure, excitement and friendship... as long as you accept that the people you call friends are also the ones you find extremely annoying. Sometimes it's even a show about cars. Follow them on their global adventure.",
        origin_country: ["US"],
        popularity: 20.104,
        media_type: "tv",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/8tnYaTYfbSzmGyHeEeBCoNUzCdZ.jpg",
    popularity: 4.922,
    media_type: "person",
  },
  {
    adult: false,
    gender: 2,
    name: "Harrison Ford",
    id: 3,
    known_for: [
      {
        id: 140607,
        video: false,
        vote_count: 14682,
        vote_average: 7.4,
        title: "Star Wars: The Force Awakens",
        release_date: "2015-12-15",
        original_language: "en",
        original_title: "Star Wars: The Force Awakens",
        genre_ids: [28, 12, 14, 878],
        backdrop_path: "/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg",
        adult: false,
        overview:
          "Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.",
        poster_path: "/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg",
        popularity: 39.544,
        media_type: "movie",
      },
      {
        id: 11,
        video: false,
        vote_count: 13937,
        vote_average: 8.2,
        title: "Star Wars",
        release_date: "1977-05-25",
        original_language: "en",
        original_title: "Star Wars",
        genre_ids: [28, 12, 878],
        backdrop_path: "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
        adult: false,
        overview:
          "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
        poster_path: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
        popularity: 70.678,
        media_type: "movie",
      },
      {
        id: 1891,
        video: false,
        vote_count: 11753,
        vote_average: 8.4,
        title: "The Empire Strikes Back",
        release_date: "1980-05-20",
        original_language: "en",
        original_title: "The Empire Strikes Back",
        genre_ids: [28, 12, 878],
        backdrop_path: "/azIbQpeKKNF9r85lBSRrNnMK0Si.jpg",
        adult: false,
        overview:
          "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
        poster_path: "/7BuH8itoSrLExs2YZSsM01Qk2no.jpg",
        popularity: 24.222,
        media_type: "movie",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/5M7oN3sznp99hWYQ9sX0xheswWX.jpg",
    popularity: 17.84,
    media_type: "person",
  },
  {
    adult: false,
    gender: 2,
    name: "Quentin Tarantino",
    id: 138,
    known_for: [
      {
        id: 680,
        video: false,
        vote_count: 19081,
        vote_average: 8.5,
        title: "Pulp Fiction",
        release_date: "1994-09-10",
        original_language: "en",
        original_title: "Pulp Fiction",
        genre_ids: [80, 53],
        backdrop_path: "/eDMZmfnH50DDboUxTRnOYYpE9aY.jpg",
        adult: false,
        overview:
          "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        poster_path: "/kK6iLyKi9Kg86qR2xPxOU94UEel.jpg",
        popularity: 45.962,
        media_type: "movie",
      },
      {
        id: 68718,
        video: false,
        vote_count: 18690,
        vote_average: 8.1,
        title: "Django Unchained",
        release_date: "2012-12-25",
        original_language: "en",
        original_title: "Django Unchained",
        genre_ids: [18, 37],
        backdrop_path: "/s4cJQaj40SwMifUrrdtdOJsjnRO.jpg",
        adult: false,
        overview:
          "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
        poster_path: "/uILtAJQpVB2wiaEgEofEEWgKW0w.jpg",
        popularity: 28.274,
        media_type: "movie",
      },
      {
        id: 16869,
        video: false,
        vote_count: 15022,
        vote_average: 8.2,
        title: "Inglourious Basterds",
        release_date: "2009-08-18",
        original_language: "en",
        original_title: "Inglourious Basterds",
        genre_ids: [28, 18, 53, 10752],
        backdrop_path: "/8pEnePgGyfUqj8Qa6d91OZQ6Aih.jpg",
        adult: false,
        overview:
          'In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as "The Basterds" are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis. The Basterds, lead by Lt. Aldo Raine soon cross paths with a French-Jewish teenage girl who runs a movie theater in Paris which is targeted by the soldiers.',
        poster_path: "/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
        popularity: 27.058,
        media_type: "movie",
      },
    ],
    known_for_department: "Directing",
    profile_path: "/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg",
    popularity: 10.374,
    media_type: "person",
  },
  {
    known_for_department: "Acting",
    adult: false,
    id: 18897,
    profile_path: "/sVuTm1w5G6ofrx4lRjy64D7MRiS.jpg",
    name: "Jackie Chan",
    known_for: [
      {
        poster_path: "/wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg",
        popularity: 20.6,
        vote_count: 7502,
        video: false,
        media_type: "movie",
        id: 9502,
        adult: false,
        backdrop_path: "/ykdS8bR7eKwjANHeVSSsdyU45ia.jpg",
        original_language: "en",
        original_title: "Kung Fu Panda",
        genre_ids: [12, 16, 35, 10751],
        title: "Kung Fu Panda",
        vote_average: 7.1,
        overview:
          "When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the \"chosen one\" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won't be easy. It's up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.",
        release_date: "2008-06-04",
      },
      {
        poster_path: "/mtqqD00vB4PGRt20gWtGqFhrkd0.jpg",
        popularity: 20.559,
        vote_count: 4439,
        video: false,
        media_type: "movie",
        id: 49444,
        adult: false,
        backdrop_path: "/iKJNE3QV0wEc9VMFuHYSZVhmSN9.jpg",
        original_language: "en",
        original_title: "Kung Fu Panda 2",
        genre_ids: [16, 10751],
        title: "Kung Fu Panda 2",
        vote_average: 6.8,
        overview:
          "Po is now living his dream as The Dragon Warrior, protecting the Valley of Peace alongside his friends and fellow kung fu masters, The Furious Five - Tigress, Crane, Mantis, Viper and Monkey. But Po’s new life of awesomeness is threatened by the emergence of a formidable villain, who plans to use a secret, unstoppable weapon to conquer China and destroy kung fu. It is up to Po and The Furious Five to journey across China to face this threat and vanquish it. But how can Po stop a weapon that can stop kung fu? He must look to his past and uncover the secrets of his mysterious origins; only then will he be able to unlock the strength he needs to succeed.",
        release_date: "2011-05-25",
      },
      {
        poster_path: "/tAMQREOoztvluqrfHiGHFVfB04B.jpg",
        popularity: 20.308,
        vote_count: 3896,
        video: false,
        media_type: "movie",
        id: 38575,
        adult: false,
        backdrop_path: "/y2Cl2LBYaabgtSLlOa4VqnOiNin.jpg",
        original_language: "en",
        original_title: "The Karate Kid",
        genre_ids: [28, 12, 18, 10751],
        title: "The Karate Kid",
        vote_average: 6.4,
        overview:
          "12-year-old Dre Parker could have been the most popular kid in Detroit, but his mother's latest career move has landed him in China. Dre immediately falls for his classmate Mei Ying but the cultural differences make such a friendship impossible. Even worse, Dre's feelings make him an enemy of the class bully, Cheng. With no friends in a strange land, Dre has nowhere to turn but maintenance man Mr. Han, who is a kung fu master. As Han teaches Dre that kung fu is not about punches and parries, but maturity and calm, Dre realizes that facing down the bullies will be the fight of his life.",
        release_date: "2010-06-10",
      },
    ],
    gender: 2,
    popularity: 22.293,
    media_type: "person",
  },
  {
    adult: false,
    gender: 2,
    name: "Michael Fassbender",
    id: 17288,
    known_for: [
      {
        id: 16869,
        video: false,
        vote_count: 15022,
        vote_average: 8.2,
        title: "Inglourious Basterds",
        release_date: "2009-08-18",
        original_language: "en",
        original_title: "Inglourious Basterds",
        genre_ids: [28, 18, 53, 10752],
        backdrop_path: "/8pEnePgGyfUqj8Qa6d91OZQ6Aih.jpg",
        adult: false,
        overview:
          'In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as "The Basterds" are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis. The Basterds, lead by Lt. Aldo Raine soon cross paths with a French-Jewish teenage girl who runs a movie theater in Paris which is targeted by the soldiers.',
        poster_path: "/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
        popularity: 27.058,
        media_type: "movie",
      },
      {
        id: 127585,
        video: false,
        vote_count: 11560,
        vote_average: 7.5,
        title: "X-Men: Days of Future Past",
        release_date: "2014-05-15",
        original_language: "en",
        original_title: "X-Men: Days of Future Past",
        genre_ids: [28, 12, 14, 878],
        backdrop_path: "/5kYj5EOQMFBFCdnk4X8KaFUfDVR.jpg",
        adult: false,
        overview:
          "The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.",
        poster_path: "/bvN8iUpHyBIvniUk4e52SUZMA7Z.jpg",
        popularity: 24.112,
        media_type: "movie",
      },
      {
        id: 1271,
        video: false,
        vote_count: 9650,
        vote_average: 7.1,
        title: "300",
        release_date: "2007-03-07",
        original_language: "en",
        original_title: "300",
        genre_ids: [28, 12, 10752],
        backdrop_path: "/6fS6Lonap7HSIcKSoBuqrDE88IM.jpg",
        adult: false,
        overview:
          "Based on Frank Miller's graphic novel, \"300\" is very loosely based the 480 B.C. Battle of Thermopylae, where the King of Sparta led his army against the advancing Persians; the battle is said to have inspired all of Greece to band together against the Persians, and helped usher in the world's first democracy.",
        poster_path: "/im6ZMuKTdLxMsDpySHjV0k17lnJ.jpg",
        popularity: 18.728,
        media_type: "movie",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/AaEfdglbUSLgdmPHWNGxDpravzg.jpg",
    popularity: 10.877,
    media_type: "person",
  },
  {
    adult: false,
    gender: 2,
    name: "David Lynch",
    id: 5602,
    known_for: [
      {
        id: 1018,
        video: false,
        vote_count: 3731,
        vote_average: 7.8,
        title: "Mulholland Drive",
        release_date: "2001-09-08",
        original_language: "en",
        original_title: "Mulholland Drive",
        genre_ids: [18, 9648, 53],
        backdrop_path: "/1P4vCGTvJc13VxejbRLbHA1dT6f.jpg",
        adult: false,
        overview:
          "Blonde Betty Elms has only just arrived in Hollywood to become a movie star when she meets an enigmatic brunette with amnesia. Meanwhile, as the two set off to solve the second woman's identity, filmmaker Adam Kesher runs into ominous trouble while casting his latest project.",
        poster_path: "/tVxGt7uffLVhIIcwuldXOMpFBPX.jpg",
        popularity: 20.211,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/oVV3M2WQfYuags2C8pGwIiNRsjz.jpg",
        genre_ids: [18, 36],
        id: 1955,
        original_language: "en",
        original_title: "The Elephant Man",
        overview:
          'A Victorian surgeon rescues a heavily disfigured man being mistreated by his "owner" as a side-show freak. Behind his monstrous façade, there is revealed a person of great intelligence and sensitivity. Based on the true story of Joseph Merrick (called John Merrick in the film), a severely deformed man in 19th century London.',
        poster_path: "/19Hc54ebzdvF3usVEmyn948U4Xr.jpg",
        release_date: "1980-10-02",
        title: "The Elephant Man",
        video: false,
        vote_average: 8.1,
        vote_count: 1931,
        popularity: 15.097,
        media_type: "movie",
      },
      {
        id: 793,
        video: false,
        vote_count: 1882,
        vote_average: 7.7,
        title: "Blue Velvet",
        release_date: "1986-09-19",
        original_language: "en",
        original_title: "Blue Velvet",
        genre_ids: [80, 9648, 53],
        backdrop_path: "/aiwNrxTMNJMRl30fWeVmSBAyXCm.jpg",
        adult: false,
        overview:
          "The discovery of a severed human ear found in a field leads a young man on an investigation related to a beautiful, mysterious nightclub singer and a group of criminals who have kidnapped her child.",
        poster_path: "/9hRKzdFIUIWsCSS5hDyBw3t1nWt.jpg",
        popularity: 15.676,
        media_type: "movie",
      },
    ],
    known_for_department: "Directing",
    profile_path: "/b6TnSpuqeOlbq7aHH9G4inmQ1v9.jpg",
    popularity: 7.404,
    media_type: "person",
  },
  {
    adult: false,
    gender: 2,
    name: "Martin Scorsese",
    id: 1032,
    known_for: [
      {
        id: 11324,
        video: false,
        vote_count: 15881,
        vote_average: 8.1,
        title: "Shutter Island",
        release_date: "2010-02-14",
        original_language: "en",
        original_title: "Shutter Island",
        genre_ids: [18, 9648, 53],
        backdrop_path: "/ntxArhtReGCqQSWFXk0c0Yt8uDO.jpg",
        adult: false,
        overview:
          "World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from a hospital for the criminally insane, but his efforts are compromised by his troubling visions and also by a mysterious doctor.",
        poster_path: "/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg",
        popularity: 34.546,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/2DZjKCPnwBKHz5VRX46rKJ9VXnz.jpg",
        genre_ids: [80, 18, 35],
        id: 106646,
        original_language: "en",
        original_title: "The Wolf of Wall Street",
        overview:
          "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
        poster_path: "/sOxr33wnRuKazR9ClHek73T8qnK.jpg",
        release_date: "2013-12-25",
        title: "The Wolf of Wall Street",
        video: false,
        vote_average: 8,
        vote_count: 15549,
        popularity: 40.362,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/9RuC3UD6mNZ0p1J6RbfJDUkQ03i.jpg",
        genre_ids: [18, 53, 80],
        id: 1422,
        original_language: "en",
        original_title: "The Departed",
        overview:
          "To take down South Boston's Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks. But both sides soon discover there's a mole among them.",
        poster_path: "/p3tmqqwFPHFdu1oVpcgKGfcPCMZ.jpg",
        release_date: "2006-10-05",
        title: "The Departed",
        video: false,
        vote_average: 8.1,
        vote_count: 9879,
        popularity: 32.695,
        media_type: "movie",
      },
    ],
    known_for_department: "Directing",
    profile_path: "/9U9Y5GQuWX3EZy39B8nkk4NY01S.jpg",
    popularity: 9.587,
    media_type: "person",
  },
  {
    known_for_department: "Acting",
    adult: false,
    id: 190,
    profile_path: "/dU35NnjZ4aGw5abIJe3WXVf3Eey.jpg",
    name: "Clint Eastwood",
    known_for: [
      {
        poster_path: "/i1U46OwMc6vlm7OoSUKfqUH615e.jpg",
        popularity: 28.727,
        vote_count: 9275,
        video: false,
        media_type: "movie",
        id: 190859,
        adult: false,
        backdrop_path: "/dcqI4l0vvGAyLsGGxobNsCVQdNK.jpg",
        original_language: "en",
        original_title: "American Sniper",
        genre_ids: [28, 10752],
        title: "American Sniper",
        vote_average: 7.4,
        overview:
          "U.S. Navy SEAL Chris Kyle takes his sole mission—protect his comrades—to heart and becomes one of the most lethal snipers in American history. His pinpoint accuracy not only saves countless lives but also makes him a prime target of insurgents. Despite grave danger and his struggle to be a good husband and father to his family back in the States, Kyle serves four tours of duty in Iraq. However, when he finally returns home, he finds that he cannot leave the war behind.",
        release_date: "2014-12-11",
      },
      {
        poster_path: "/w3zz8djZKknVpkpHi0I7kqibzbC.jpg",
        popularity: 19.883,
        vote_count: 7247,
        video: false,
        media_type: "movie",
        id: 13223,
        adult: false,
        backdrop_path: "/wmsePXV2z1b6ecXuKKrFbG0Q92P.jpg",
        original_language: "en",
        original_title: "Gran Torino",
        genre_ids: [18],
        title: "Gran Torino",
        vote_average: 8,
        overview:
          "Widower Walt Kowalski is a grumpy, prejudiced, tough-minded, unhappy, old, Korean War veteran who can't get along with either his kids or his neighbours. His prize possession is a 1972 Gran Torino he keeps in mint condition. When his neighbour, Thao—a young Hmong teenager under pressure from his gang member cousin—tries to steal his Gran Torino, Walt sets out to reform the youth and takes steps to protect Thao and his family from the gangs that infest their neighborhood.",
        release_date: "2008-12-09",
      },
      {
        poster_path: "/jcfEqKdWF1zeyvECPqp3mkWLct2.jpg",
        popularity: 21.75,
        vote_count: 6143,
        video: false,
        media_type: "movie",
        id: 70,
        adult: false,
        backdrop_path: "/jruBJZOJCQAWWhJ20UbxPUpbXXT.jpg",
        original_language: "en",
        original_title: "Million Dollar Baby",
        genre_ids: [18],
        title: "Million Dollar Baby",
        vote_average: 7.9,
        overview:
          "Despondent over a painful estrangement from his daughter, trainer Frankie Dunn isn't prepared for boxer Maggie Fitzgerald to enter his life. But Maggie's determined to go pro and to convince Dunn and his cohort to help her.",
        release_date: "2004-12-15",
      },
    ],
    gender: 2,
    popularity: 17.725,
    media_type: "person",
  },
  {
    known_for_department: "Directing",
    adult: false,
    id: 525,
    profile_path: "/iG0Gs0i5yd6SG4tSFjlXi5ZnSX6.jpg",
    name: "Christopher Nolan",
    known_for: [
      {
        poster_path: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
        popularity: 65.045,
        vote_count: 26448,
        video: false,
        media_type: "movie",
        id: 27205,
        adult: false,
        backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
        original_language: "en",
        original_title: "Inception",
        genre_ids: [28, 12, 878],
        title: "Inception",
        vote_average: 8.3,
        overview:
          "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
        release_date: "2010-07-15",
      },
      {
        poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        popularity: 89.478,
        vote_count: 23021,
        video: false,
        media_type: "movie",
        id: 157336,
        adult: false,
        backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
        original_language: "en",
        original_title: "Interstellar",
        genre_ids: [12, 18, 878],
        title: "Interstellar",
        vote_average: 8.3,
        overview:
          "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
        release_date: "2014-11-05",
      },
      {
        poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        popularity: 60.29,
        vote_count: 22750,
        video: false,
        media_type: "movie",
        id: 155,
        adult: false,
        backdrop_path: "/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
        original_language: "en",
        original_title: "The Dark Knight",
        genre_ids: [28, 80, 18, 53],
        title: "The Dark Knight",
        vote_average: 8.4,
        overview:
          "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        release_date: "2008-07-16",
      },
    ],
    gender: 2,
    popularity: 8.205,
    media_type: "person",
  },
  {
    known_for_department: "Acting",
    adult: false,
    id: 10859,
    profile_path: "/h1co81QaT2nJA41Sb7eZwmWl1L2.jpg",
    name: "Ryan Reynolds",
    known_for: [
      {
        poster_path: "/yGSxMiF0cYuAiyuve5DA6bnWEOI.jpg",
        popularity: 36.75,
        vote_count: 23162,
        video: false,
        media_type: "movie",
        id: 293660,
        adult: false,
        backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
        original_language: "en",
        original_title: "Deadpool",
        genre_ids: [28, 12, 35],
        title: "Deadpool",
        vote_average: 7.6,
        overview:
          "Deadpool tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
        release_date: "2016-02-09",
      },
      {
        poster_path: "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
        popularity: 43.596,
        vote_count: 11657,
        video: false,
        media_type: "movie",
        id: 383498,
        adult: false,
        backdrop_path: "/3P52oz9HPQWxcwHOwxtyrVV1LKi.jpg",
        original_language: "en",
        original_title: "Deadpool 2",
        genre_ids: [28, 12, 35],
        title: "Deadpool 2",
        vote_average: 7.5,
        overview:
          "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
        release_date: "2018-05-10",
      },
      {
        poster_path: "/rf6k1sjGSVavqLhwyYoKeOuExez.jpg",
        popularity: 18.448,
        vote_count: 8986,
        video: false,
        media_type: "movie",
        id: 72105,
        adult: false,
        backdrop_path: "/dNznSMEcNW3XTcruhBMAT6QQo5N.jpg",
        original_language: "en",
        original_title: "Ted",
        genre_ids: [35, 14],
        title: "Ted",
        vote_average: 6.3,
        overview:
          "John Bennett, a man whose childhood wish of bringing his teddy bear to life came true, now must decide between keeping the relationship with the bear or his girlfriend, Lori.",
        release_date: "2012-06-29",
      },
    ],
    gender: 2,
    popularity: 20.173,
    media_type: "person",
  },
  {
    known_for_department: "Acting",
    adult: false,
    id: 1245,
    profile_path: "/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg",
    name: "Scarlett Johansson",
    known_for: [
      {
        poster_path: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
        popularity: 37.498,
        vote_count: 22747,
        video: false,
        media_type: "movie",
        id: 24428,
        adult: false,
        backdrop_path: "/kwUQFeFXOOpgloMgZaadhzkbTI4.jpg",
        original_language: "en",
        original_title: "The Avengers",
        genre_ids: [28, 12, 878],
        title: "The Avengers",
        vote_average: 7.7,
        overview:
          "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
        release_date: "2012-04-25",
      },
      {
        poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
        popularity: 91.91,
        vote_count: 18898,
        video: false,
        media_type: "movie",
        id: 299536,
        adult: false,
        backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
        original_language: "en",
        original_title: "Avengers: Infinity War",
        genre_ids: [28, 12, 878],
        title: "Avengers: Infinity War",
        vote_average: 8.3,
        overview:
          "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
        release_date: "2018-04-25",
      },
      {
        poster_path: "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
        popularity: 46.401,
        vote_count: 16453,
        video: false,
        media_type: "movie",
        id: 271110,
        adult: false,
        backdrop_path: "/7FWlcZq3r6525LWOcvO9kNWurN1.jpg",
        original_language: "en",
        original_title: "Captain America: Civil War",
        genre_ids: [28, 12, 878],
        title: "Captain America: Civil War",
        vote_average: 7.4,
        overview:
          "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
        release_date: "2016-04-27",
      },
    ],
    gender: 1,
    popularity: 40.355,
    media_type: "person",
  },
  {
    known_for_department: "Acting",
    adult: false,
    id: 500,
    profile_path: "/gThaIXgpCm3PCiXwFNDBJCme85y.jpg",
    name: "Tom Cruise",
    known_for: [
      {
        poster_path: "/uUHvlkLavotfGsNtosDy8ShsIYF.jpg",
        popularity: 27.092,
        vote_count: 9633,
        video: false,
        media_type: "movie",
        id: 137113,
        adult: false,
        backdrop_path: "/auZIuHEUec5tBTns3tCRXfayxZq.jpg",
        original_language: "en",
        original_title: "Edge of Tomorrow",
        genre_ids: [28, 878],
        title: "Edge of Tomorrow",
        vote_average: 7.6,
        overview:
          "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.",
        release_date: "2014-05-27",
      },
      {
        poster_path: "/2ncs7hqBsEjFMqt6Y7ShBCO9tWs.jpg",
        popularity: 23.588,
        vote_count: 7922,
        video: false,
        media_type: "movie",
        id: 75612,
        adult: false,
        backdrop_path: "/Pv6vu1lxgct3GWhUXVVOMZwNlZ.jpg",
        original_language: "en",
        original_title: "Oblivion",
        genre_ids: [28, 12, 9648, 878],
        title: "Oblivion",
        vote_average: 6.6,
        overview:
          "Jack Harper is one of the last few drone repairmen stationed on Earth.  Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack’s mission is nearly complete.  His existence is brought crashing down when he rescues a beautiful  stranger from a downed spacecraft.  Her arrival triggers a chain of events that  forces him to question everything he knows and puts the fate of humanity in his hands.",
        release_date: "2013-04-10",
      },
      {
        poster_path: "/7GCKNRbzcA4rJXAKoE8KS9IDnZP.jpg",
        popularity: 24.032,
        vote_count: 7065,
        video: false,
        media_type: "movie",
        id: 56292,
        adult: false,
        backdrop_path: "/zNyNPn86myH5Ix1demDa5dfYDao.jpg",
        original_language: "en",
        original_title: "Mission: Impossible - Ghost Protocol",
        genre_ids: [28, 12, 53],
        title: "Mission: Impossible - Ghost Protocol",
        vote_average: 7,
        overview:
          "Ethan Hunt and his team are racing against time to track down a dangerous terrorist named Hendricks, who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.",
        release_date: "2011-12-07",
      },
    ],
    gender: 2,
    popularity: 18.607,
    media_type: "person",
  },
  {
    adult: false,
    gender: 2,
    name: "Spike Lee",
    id: 5281,
    known_for: [
      {
        id: 487558,
        video: false,
        vote_count: 4829,
        vote_average: 7.6,
        title: "BlacKkKlansman",
        release_date: "2018-07-30",
        original_language: "en",
        original_title: "BlacKkKlansman",
        genre_ids: [35, 80, 18, 36],
        backdrop_path: "/9Uh5xR04t66XFiFag1BKVyPyHqz.jpg",
        adult: false,
        overview:
          "Colorado Springs, late 1970s. Ron Stallworth, an African American police officer, and Flip Zimmerman, his Jewish colleague, run an undercover operation to infiltrate the Ku Klux Klan.",
        poster_path: "/8jxqAvSDoneSKRczaK8v9X5gqBp.jpg",
        popularity: 19.227,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/8b4vDh7hNSLZKyAYUnZJalExbJb.jpg",
        genre_ids: [80, 18, 53],
        id: 388,
        original_language: "en",
        original_title: "Inside Man",
        overview:
          "When an armed, masked gang enter a Manhattan bank, lock the doors and take hostages, the detective assigned to effect their release enters negotiations preoccupied with corruption charges he is facing.",
        poster_path: "/mf4i9zZVXMmqWsEb9D0OAY7k3t.jpg",
        release_date: "2006-03-17",
        title: "Inside Man",
        video: false,
        vote_average: 7.4,
        vote_count: 3655,
        popularity: 24.509,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/HEZ8kx7vEYO4q4F9BhvnCKpUKh.jpg",
        genre_ids: [80, 18],
        id: 1429,
        original_language: "en",
        original_title: "25th Hour",
        overview:
          "In New York City in the days following the events of 9/11, Monty Brogan is a convicted drug dealer about to start a seven-year prison sentence, and his final hours of freedom are devoted to hanging out with his closest buddies and trying to prepare his girlfriend for his extended absence.",
        poster_path: "/8AYVa7X4kMlQkn1sC6nVyKnzikV.jpg",
        release_date: "2002-12-16",
        title: "25th Hour",
        video: false,
        vote_average: 7.4,
        vote_count: 1459,
        popularity: 13.574,
        media_type: "movie",
      },
    ],
    known_for_department: "Directing",
    profile_path: "/2KOHXgk2uoRXl6u7V9xpAIo3uay.jpg",
    popularity: 4.889,
    media_type: "person",
  },
  {
    adult: false,
    gender: 1,
    name: "Jennifer Lawrence",
    id: 72129,
    known_for: [
      {
        id: 70160,
        video: false,
        vote_count: 16610,
        vote_average: 7.1,
        title: "The Hunger Games",
        release_date: "2012-03-12",
        original_language: "en",
        original_title: "The Hunger Games",
        genre_ids: [12, 14, 878],
        backdrop_path: "/zqAtFrTmauJGRbqrL0XoENa2eL.jpg",
        adult: false,
        overview:
          "Every year in the ruins of what was once North America, the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games.  Part twisted entertainment, part government intimidation tactic, the Hunger Games are a nationally televised event in which “Tributes” must fight with one another until one survivor remains.  Pitted against highly-trained Tributes who have prepared for these Games their entire lives, Katniss is forced to rely upon her sharp instincts as well as the mentorship of drunken former victor Haymitch Abernathy.  If she’s ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love. The world will be watching.",
        poster_path: "/mgZKtOvxtDX5HtUa5fAVQ5d1Afh.jpg",
        popularity: 16.821,
        media_type: "movie",
      },
      {
        id: 101299,
        video: false,
        vote_count: 12881,
        vote_average: 7.4,
        title: "The Hunger Games: Catching Fire",
        release_date: "2013-11-15",
        original_language: "en",
        original_title: "The Hunger Games: Catching Fire",
        genre_ids: [28, 12, 878],
        backdrop_path: "/rSWsiFngPkXBDH1YwRJ4xAwZJTp.jpg",
        adult: false,
        overview:
          'Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a "Victor\'s Tour" of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.',
        poster_path: "/7c1JtraYsjMMnk8Md0IMoyRzqZJ.jpg",
        popularity: 24.097,
        media_type: "movie",
      },
      {
        id: 131631,
        video: false,
        vote_count: 11682,
        vote_average: 6.8,
        title: "The Hunger Games: Mockingjay - Part 1",
        release_date: "2014-11-19",
        original_language: "en",
        original_title: "The Hunger Games: Mockingjay - Part 1",
        genre_ids: [12, 878, 53],
        backdrop_path: "/rYsdoUqkltpKZQWwCWXf55csXvL.jpg",
        adult: false,
        overview:
          "Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
        poster_path: "/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
        popularity: 38.923,
        media_type: "movie",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/hvMB8ItfetI8baJJ15XgI4gITqf.jpg",
    popularity: 19.407,
    media_type: "person",
  },
  {
    adult: false,
    gender: 2,
    name: "Theodor Pištěk",
    id: 147211,
    known_for: [
      {
        adult: false,
        backdrop_path: "/eoDbk2Gk7Sb2q7LUlG32NtdMZau.jpg",
        genre_ids: [35, 14],
        id: 36918,
        original_language: "cs",
        original_title: "Císařův pekař – Pekařův císař",
        overview:
          "The Emperor's mismanagement of his country is provoking some in his court to plot to overthrow him.  He feels successful, at least, when he discovers the legendary Golem, which he believes can protect him and even cure his imaginary illnesses but, when he disappears while on a bender, his kindly baker, who looks just like him, is mistaken for him, and begins to put things in order.  However, the conspirators, not to be outdone, determine to bring the Golem back to life to do their bidding.",
        poster_path: "/3i6VoJXD5EMmNCN1f7DTvZMzJnJ.jpg",
        release_date: "1952-01-04",
        title: "The Emperor and the Golem",
        video: false,
        vote_average: 7.5,
        vote_count: 17,
        popularity: 3.959,
        media_type: "movie",
      },
      {
        id: 51959,
        video: false,
        vote_count: 15,
        vote_average: 6.6,
        title: "The Princess with the Golden Star",
        release_date: "1959-12-18",
        original_language: "cs",
        original_title: "Princezna se zlatou hvězdou",
        genre_ids: [14, 10751],
        backdrop_path: "/58urVpxmJWN5Af3dTQ5DcrwZjK2.jpg",
        adult: false,
        overview: "",
        poster_path: "/4wBC5VGvzABMoEcY32eSYOdY9u8.jpg",
        popularity: 6.174,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/qkdcAO2GW1KWT3apiA6kY7CyPxl.jpg",
        genre_ids: [18, 10749],
        id: 190091,
        original_language: "cs",
        original_title: "Erotikon",
        overview:
          "Andrea, a beautiful daughter of a railway gateman, is seduced by a rich passenger, who missed his train. Left pregnant, Andrea marries another man and moves to Prague, only to encounter her former lover and recover her former lust.",
        poster_path: "/cvj24f55BVPpwN1tTrlPLZSq80j.jpg",
        release_date: "1929-07-12",
        title: "Erotikon",
        video: false,
        vote_average: 6.7,
        vote_count: 10,
        popularity: 1.273,
        media_type: "movie",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/5Yuw85ZefamwQZcYCoyoWqcD3TC.jpg",
    popularity: 1.27,
    media_type: "person",
  },
  {
    adult: false,
    gender: 1,
    name: "Amy Adams",
    id: 9273,
    known_for: [
      {
        id: 209112,
        video: false,
        vote_count: 13604,
        vote_average: 5.8,
        title: "Batman v Superman: Dawn of Justice",
        release_date: "2016-03-23",
        original_language: "en",
        original_title: "Batman v Superman: Dawn of Justice",
        genre_ids: [28, 12, 14],
        backdrop_path: "/doiUtOHzcxXFl0GVQ2n8Ay6Pirx.jpg",
        adult: false,
        overview:
          "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
        poster_path: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
        popularity: 29.666,
        media_type: "movie",
      },
      {
        id: 329865,
        video: false,
        vote_count: 12445,
        vote_average: 7.5,
        title: "Arrival",
        release_date: "2016-11-10",
        original_language: "en",
        original_title: "Arrival",
        genre_ids: [18, 9648, 878],
        backdrop_path: "/hNCqkXbWd40eftqSdjq8TmV7Mqr.jpg",
        adult: false,
        overview:
          "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
        poster_path: "/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
        popularity: 34.034,
        media_type: "movie",
      },
      {
        id: 49521,
        video: false,
        vote_count: 11144,
        vote_average: 6.5,
        title: "Man of Steel",
        release_date: "2013-06-12",
        original_language: "en",
        original_title: "Man of Steel",
        genre_ids: [28, 12, 14, 878],
        backdrop_path: "/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg",
        adult: false,
        overview:
          "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.",
        poster_path: "/7rIPjn5TUK04O25ZkMyHrGNPgLx.jpg",
        popularity: 48.216,
        media_type: "movie",
      },
    ],
    known_for_department: "Acting",
    profile_path: "/1h2r2VTpoFb5QefAaBYYQgQzL9z.jpg",
    popularity: 11.073,
    media_type: "person",
  },
];
