import { MovieItemAttr } from "../../components/Carousel/types";

export const dummyMovies: MovieItemAttr[] = [
  {
    id: 547016,
    video: false,
    vote_count: 669,
    vote_average: 7.3,
    title: "The Old Guard",
    release_date: "2020-07-10",
    original_language: "en",
    original_title: "The Old Guard",
    genre_ids: [28, 14],
    backdrop_path: "/m0ObOaJBerZ3Unc74l471ar8Iiy.jpg",
    adult: false,
    overview:
      "Four undying warriors who've secretly protected humanity for centuries become targeted for their mysterious powers just as they discover a new immortal.",
    poster_path: "/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg",
    popularity: 351.438,
  },
  {
    id: 516486,
    video: false,
    vote_count: 148,
    vote_average: 7,
    title: "Greyhound",
    release_date: "2020-07-10",
    original_language: "en",
    original_title: "Greyhound",
    genre_ids: [28, 18, 10752],
    backdrop_path: "/xXBnM6uSTk6qqCf0SRZKXcga9Ba.jpg",
    adult: false,
    overview:
      "A first-time captain leads a convoy of allied ships carrying thousands of soldiers across the treacherous waters of the “Black Pit” to the front lines of WW2. With no air cover protection for 5 days, the captain and his convoy must battle the surrounding enemy Nazi U-boats in order to give the allies a chance to win the war.",
    poster_path: "/AsdB9A2XGalCZVjlyG9tRf03IfW.jpg",
    popularity: 351.193,
  },
  {
    id: 587792,
    video: false,
    vote_count: 105,
    vote_average: 7.9,
    title: "Palm Springs",
    release_date: "2020-01-26",
    original_language: "en",
    original_title: "Palm Springs",
    genre_ids: [35, 878, 10749],
    backdrop_path: "/d7JUXVvjvVCXWs1mlpyO5ESdWdT.jpg",
    adult: false,
    overview:
      "When carefree Nyles and reluctant maid of honor Sarah have a chance encounter at a Palm Springs wedding, things get complicated as they are unable to escape the venue, themselves, or each other.",
    poster_path: "/yf5IuMW6GHghu39kxA0oFx7Bxmj.jpg",
    popularity: 66.585,
  },
  {
    id: 299534,
    video: false,
    vote_count: 14114,
    vote_average: 8.3,
    title: "Avengers: Endgame",
    release_date: "2019-04-24",
    original_language: "en",
    original_title: "Avengers: Endgame",
    genre_ids: [28, 12, 878],
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    adult: false,
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    popularity: 72.622,
  },
  {
    id: 539181,
    video: false,
    vote_count: 32,
    vote_average: 6.6,
    title: "Relic",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Relic",
    genre_ids: [18, 27],
    backdrop_path: "/vpUUznNzW85xo02H16RaSxRNS1.jpg",
    adult: false,
    overview:
      "When Edna, the elderly and widowed matriarch of the family, goes missing, her daughter Kay and granddaughter Sam travel to their remote family home to find her. Soon after her return, they start to discover a sinister presence haunting the house and taking control of Edna.",
    poster_path: "/3wZ0gxLqsPleneFSTZILmM3BE8Q.jpg",
    popularity: 87.111,
  },
  {
    id: 606234,
    video: false,
    vote_count: 7,
    vote_average: 8.4,
    title: "Archive",
    release_date: "2020-07-01",
    original_language: "en",
    original_title: "Archive",
    genre_ids: [878],
    backdrop_path: "/ckRBJIHrUhQMMkEhuk4iW2NIBWP.jpg",
    adult: false,
    overview:
      "2038: George Almore is working on a true human-equivalent AI, and his latest prototype is almost ready. This sensitive phase is also the riskiest as he has a goal that must be hidden at all costs—being reunited with his dead wife.",
    poster_path: "/q9t1AxbzyGQENDunK1GT8OS4aJl.jpg",
    popularity: 53.994,
  },
  {
    id: 556574,
    video: false,
    vote_count: 220,
    vote_average: 8.6,
    title: "Hamilton",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Hamilton",
    genre_ids: [18, 36, 10402],
    backdrop_path: "/uWVkEo9PWHu9algZsiLPi6sRU64.jpg",
    adult: false,
    overview:
      "Presenting the tale of American founding father Alexander Hamilton, this filmed version of the original Broadway smash hit is the story of America then, told by America now.",
    poster_path: "/h1B7tW0t399VDjAcWJh8m87469b.jpg",
    popularity: 82.625,
  },
  {
    id: 385103,
    video: false,
    vote_count: 1226,
    vote_average: 8,
    title: "Scoob!",
    release_date: "2020-05-15",
    original_language: "en",
    original_title: "Scoob!",
    genre_ids: [12, 16, 35, 9648, 10751],
    backdrop_path: "/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg",
    adult: false,
    overview:
      "In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.",
    poster_path: "/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg",
    popularity: 100.079,
  },
  {
    id: 11,
    video: false,
    vote_count: 13945,
    vote_average: 8.2,
    title: "Star Wars",
    release_date: "1977-05-25",
    original_language: "en",
    original_title: "Star Wars",
    genre_ids: [28, 12, 878],
    backdrop_path: "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
    adult: false,
    overview:
      "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
    poster_path: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    popularity: 68.052,
  },
  {
    adult: false,
    backdrop_path: "/yOBBzBlN72C6QLtXaskQ87fdVkS.jpg",
    genre_ids: [28, 12, 36],
    id: 635237,
    original_language: "fr",
    original_title: "Arthur & Merlin: Knights of Camelot",
    overview:
      "King Arthur returns home after fighting the Roman Empire. His illegitimate son has corrupted the throne of Camelot and King Arthur must reunite with the wizard Merlin and the Knights of the Round Table to fight to get back his crown.",
    poster_path: "/chGTXsvn53XvEnvsJ9ZD9eiYKx9.jpg",
    release_date: "2020-05-28",
    title: "Arthur & Merlin: Knights of Camelot",
    video: false,
    vote_average: 2.1,
    vote_count: 8,
    popularity: 4.74,
  },
  {
    id: 495764,
    video: false,
    vote_count: 4953,
    vote_average: 7.2,
    title:
      "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
    release_date: "2020-02-05",
    original_language: "en",
    original_title:
      "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
    genre_ids: [28, 35, 80, 18],
    backdrop_path: "/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg",
    adult: false,
    overview:
      "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
    poster_path: "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
    popularity: 98.917,
  },
  {
    id: 556678,
    video: false,
    vote_count: 382,
    vote_average: 7,
    title: "Emma.",
    release_date: "2020-02-13",
    original_language: "en",
    original_title: "Emma.",
    genre_ids: [35, 18, 10749],
    backdrop_path: "/5GbkL9DDRzq3A21nR7Gkv6cFGjq.jpg",
    adult: false,
    overview:
      "In 1800s England, a well-meaning but selfish young woman meddles in the love lives of her friends.",
    poster_path: "/uHpHzbHLSsVmAuuGuQSpyVDZmDc.jpg",
    popularity: 41.656,
  },
  {
    id: 531876,
    video: false,
    vote_count: 126,
    vote_average: 7,
    title: "The Outpost",
    release_date: "2020-06-24",
    original_language: "en",
    original_title: "The Outpost",
    genre_ids: [28, 18, 36, 10752],
    backdrop_path: "/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg",
    adult: false,
    overview:
      "A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.",
    poster_path: "/hPkqY2EMqWUnFEoedukilIUieVG.jpg",
    popularity: 117.321,
  },
  {
    id: 686245,
    video: false,
    vote_count: 11,
    vote_average: 5.2,
    title: "Survive the Night",
    release_date: "2020-07-09",
    original_language: "en",
    original_title: "Survive the Night",
    genre_ids: [28, 53],
    backdrop_path: "/cVnCwyaKP7exbgaCMR9DJS4xleZ.jpg",
    adult: false,
    overview:
      "A disgraced doctor and his family are held hostage at their home by criminals on the run, when a robbery-gone-awry requires them to seek immediate medical attention.",
    poster_path: "/niyXFhGIk4W2WTcX2Eod8vx2Mfe.jpg",
    popularity: 48.775,
  },
  {
    id: 428045,
    video: false,
    vote_count: 99,
    vote_average: 5.9,
    title: "Journey to China: The Mystery of Iron Mask",
    release_date: "2019-08-16",
    original_language: "ru",
    original_title: "Тайна Печати дракона",
    genre_ids: [12, 14],
    backdrop_path: "/5yiCqzmxYv36GGdc05egCMHedbX.jpg",
    adult: false,
    overview:
      "The Russian Czar Peter the Great commissions Jonathan Green, an English traveller, to map the Far East territories of the Russian Empire. Green sets off on yet another long journey, full of unbelievable adventures, which eventually leads him to China. On his way, the famous cartographer makes breath-taking discoveries, meets mysterious creatures, Chinese princesses, deadly masters of oriental martial arts, and even Lun Van, the King of Dragons, himself. What could be more perilous than looking into the eyes of Viy? Only meeting him again… What will prevail this time — the unflinching scepticism of the scientist or ancient black magic, which has already gained influence over the Far East Lands?",
    poster_path: "/GAeK18hkfR6rzlo1vITvQhoEiW.jpg",
    popularity: 76.241,
  },
  {
    id: 451184,
    video: false,
    vote_count: 107,
    vote_average: 6.3,
    title: "Wasp Network",
    release_date: "2020-01-29",
    original_language: "en",
    original_title: "Wasp Network",
    genre_ids: [18, 36, 53],
    backdrop_path: "/72r4uAQGsa8KEv0DB2TpSu31lEB.jpg",
    adult: false,
    overview:
      "Havana, Cuba, 1990. René González, an airplane pilot, unexpectedly flees the country, leaving behind his wife Olga and his daughter Irma, and begins a new life in Miami, where he becomes a member of an anti-Castro organization.",
    poster_path: "/fOvqEunubL3wPskvtk2Ficfl0pH.jpg",
    popularity: 54.082,
  },
  {
    id: 508439,
    video: false,
    vote_count: 2522,
    vote_average: 7.9,
    title: "Onward",
    release_date: "2020-02-29",
    original_language: "en",
    original_title: "Onward",
    genre_ids: [12, 16, 35, 14, 10751],
    backdrop_path: "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
    adult: false,
    overview:
      "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
    poster_path: "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
    popularity: 67.737,
  },
  {
    id: 181812,
    video: false,
    vote_count: 5205,
    vote_average: 6.6,
    title: "Star Wars: The Rise of Skywalker",
    release_date: "2019-12-18",
    original_language: "en",
    original_title: "Star Wars: The Rise of Skywalker",
    genre_ids: [28, 12, 878],
    backdrop_path: "/SPkEiZGxq5aHWQ2Zw7AITwSEo2.jpg",
    adult: false,
    overview:
      "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
    poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
    popularity: 63.217,
  },
  {
    id: 706510,
    video: false,
    vote_count: 162,
    vote_average: 6.5,
    title: "Desperados",
    release_date: "2020-07-03",
    original_language: "en",
    original_title: "Desperados",
    genre_ids: [35, 10749],
    backdrop_path: "/k8H6Qp4uJ9WHArPQwDqCaW9g3Sj.jpg",
    adult: false,
    overview:
      "A panicked young woman and her two best friends fly to Mexico to delete a ranting email she sent to her new boyfriend. On arrival, they run into her former beau, who soon gets caught up in their frantic scheme.",
    poster_path: "/hoUzSMxGu4Bm73EvH6B3iceFwW8.jpg",
    popularity: 76.859,
  },
  {
    id: 522627,
    video: false,
    vote_count: 1599,
    vote_average: 7.7,
    title: "The Gentlemen",
    release_date: "2020-01-01",
    original_language: "en",
    original_title: "The Gentlemen",
    genre_ids: [28, 35, 80],
    backdrop_path: "/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg",
    adult: false,
    overview:
      "American expat Mickey Pearson has built a highly profitable marijuana empire in London. When word gets out that he’s looking to cash out of the business forever it triggers plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
    poster_path: "/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg",
    popularity: 53.234,
  },
];
